// src/pages/code/innovation/clock/index.vue
<!------------------------------------  时钟  ------------------------------------------------->
<script lang="ts" setup>
import { useGetTime } from '@/hooks'

const time = useGetTime()

const hourHandStyle = computed(() => {
  const degrees = (time.value.hour24 % 12) * 30 + time.value.minute * 0.5

  return `transform: rotate(${degrees}deg)`
})

const minuteHandStyle = computed(() => {
  const degrees = time.value.minute * 6 + time.value.second * 0.1

  return `transform: rotate(${degrees}deg)`
})

const secondHandStyle = computed(() => {
  const degrees = time.value.second * 6

  return `transform: rotate(${degrees}deg)`
})

</script>

<template>
  <div
    class="h-full w-full flex items-center justify-center"
  >
    <div
      class="h-full w-full flex justify-center justify-between bg-#1e1f26"
    >

      <div
        class="relative aspect-square h-full flex items-center justify-center bg-#1e1f26"
      >
        <div
          class="clock"
        >
          <div
            v-for="num in 12"
            :key="num"
            class="absolute h-90% text-6 color-white font-700"
            :style="{
              transform: `rotate(${num * 30}deg)`,
            }"
          >
            <div
              :style="{
                transform: `rotate(${num * -30}deg)`,
              }"
            >
              {{ num }}
            </div>
          </div>

          <div
            :style="hourHandStyle"
            class="absolute left-1/2 top-3/10 z-0 h-1/5 w-[4px] origin-bottom transform transform rounded-full bg-[#FFF] -ml-1px"
          />

          <div
            :style="minuteHandStyle"
            class="absolute top-1/4 z-1 h-1/4 w-3px origin-bottom transform rounded-full bg-[#FFF]"
          />

          <div
            :style="secondHandStyle"
            class="absolute left-1/2 top-1/6 h-1/3 w-2px origin-bottom transform rounded-full bg-#FF0000"
          />
        </div>
      </div>

      <div
        class="flex flex-col flex-1 items-center justify-center text-6 text-white font-700"
      >
        <div>
          星期{{ time.week }}
        </div>

        <div>
          {{ time.hour24Formatted }} : {{ time.minuteFormatted }} : {{ time.secondFormatted }}
        </div>

        <div>
          {{ time.year }} 年 {{ time.month }} 月 {{ time.day }}日
        </div>

      </div>
    </div>
  </div>
</template>

<style lang="less" scoped>
.clock {
  position: relative;
  background-color: #1e1f26;
  background-size: cover;
  background-position: center center;
  height: 80%;
  width: 80%;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  border: 4px solid #1e1f26;
  box-shadow:
    0 -1.5vmin 1.5vmin rgba(255, 255, 255, 0.05),
    inset 0 -1.5vmin 1.5vmin rgba(255, 255, 255, 0.05),
    0 1.5vmin 1.5vmin rgba(0, 0, 0, 0.3),
    inset 0 1.5vmin 1.5vmin rgba(0, 0, 0, 0.3);
  transition: all 0.4s ease;
  &:before {
    content: '';
    height: 8px;
    width: 8px;
    background-color: #ccc;
    border: 0.2vmin solid #1e1f26;
    position: absolute;
    border-radius: 50%;
    z-index: 1000;
    transition: all ease 0.2s;
  }
}
</style>

// src/pages/blog/creativity/clock/index.tsx
import Card from "@/components/card";
import { useGetTime } from "@/hooks";
import { useMemo } from "react";
import styles from "./index.module.less";

function Clock() {
	const time = useGetTime();

	/**
	 *  计算时针样式
	 */
	const hourHandStyle = useMemo(() => {
		const degrees = (time.hour24 % 12) * 30 + time.minute * 0.5;
		return { transform: `rotate(${degrees}deg)` };
	}, [time.hour24, time.minute]);

	/**
	 *  计算分针样式
	 */
	const minuteHandStyle = useMemo(() => {
		const degrees = time.minute * 6 + time.second * 0.1;
		return { transform: `rotate(${degrees}deg)` };
	}, [time.minute, time.second]);

	/**
	 *  计算秒针样式
	 */
	const secondHandStyle = useMemo(() => {
		const degrees = time.second * 6;
		return { transform: `rotate(${degrees}deg)` };
	}, [time.second]);

	if (!time || !hourHandStyle || !minuteHandStyle || !secondHandStyle) {
		return null;
	}

	return (
		<Card className="h-full w-full">
			<div className="relative aspect-square max-w-full max-h-full h-full w-full flex items-center justify-center bg-[#1e1f26] rounded-xl m-auto">
				<div className={`relative ${styles.clock}`}>
					{/* 渲染表盘数字 */}
					{Array.from({ length: 12 }).map((_, index) => {
						/**
						 *  数字从 1 到 12
						 */
						const num = index + 1;
						return (
							<div
								key={num}
								className="absolute h-[90%] text-[24px] text-[#fff] font-bold"
								style={{ transform: `rotate(${num * 30}deg)` }}
							>
								<div style={{ transform: `rotate(${num * -30}deg)` }}>
									{num}
								</div>
							</div>
						);
					})}

					{/* 时钟指针 */}
					<div
						style={hourHandStyle}
						className="absolute left-1/2 top-[30%] z-0 h-[20%] w-[6px] origin-bottom rounded-full bg-[#fff] ml-[-3px]"
					/>
					<div
						style={minuteHandStyle}
						className="absolute top-1/4 z-1 h-[25%] w-[3px] origin-bottom rounded-full bg-[#FFF]"
					/>
					<div
						style={secondHandStyle}
						className="absolute left-1/2 top-[16.67%] h-[33%] w-[2px] origin-bottom rounded-full bg-[#FF0000] ml-[-1px]"
					/>
				</div>
			</div>
		</Card>
	);
}

export default Clock;
