// src/pages/admin/news/weather/index.vue
<script lang="ts" setup>
import type { CascaderValue } from 'element-plus'

import type { WeatherType } from './types'

import { AdminApi } from '@/apis'

import Climate from './components/climate/index.vue'

import Meter from './components/meter/index.vue'

import PassedChart from './components/passedChart/index.vue'

import TempChart from './components/tempChart/index.vue'

import { provinceCityData } from './data'

const isLoading = ref(false)

const province = ref('AHN') // 当前选择的省份

const city = ref('zOenJ')

const data = ref<WeatherType>({
  real: {
    station: {
      code: 'defaultCode',
      province: 'defaultProvince',
      city: 'defaultCity',
      url: 'http://default.url',
    },
    publish_time: '2024-01-01T00:00:00Z',
    weather: {
      temperature: 0,
      temperatureDiff: 0,
      airpressure: 1013,
      humidity: 50,
      rain: 0,
      rcomfort: 0,
      icomfort: 0,
      info: 'Clear',
      img: '01',
      feelst: 20,
    },
    wind: {
      direct: 'North',
      degree: 0,
      power: '1级',
      speed: 0,
    },
    warn: {
      alert: 'No warnings',
      pic: '',
      province: '',
      city: '',
      url: '',
      issuecontent: '',
      fmeans: '',
      signaltype: '',
      signallevel: '',
      pic2: '',
    },
    sunriseSunset: {
      sunrise: '06:00',
      sunset: '18:00',
    },
  },
  predict: {
    station: {
      code: 'defaultCode',
      province: 'defaultProvince',
      city: 'defaultCity',
      url: 'http://default.url',
    },
    publish_time: '2024-01-01T00:00:00Z',
    detail: [],
  },
  air: {
    forecasttime: '2024-12-19 15:00',
    aqi: 91,
    aq: 2,
    text: '良',
    aqiCode: '99031;99032;99033;99035;99037;99038;99039;99040',
  },
  tempchart: [],
  passedchart: [],
  climate: {
    time: '',
    month: [],
  },
  radar: {
    title: '实时雷达数据',
    image: '',
    url: '',
  },
})

/**
 * 清空数据
 */
function clearData() {
  data.value = {
    real: {
      station: {
        code: 'defaultCode',
        province: 'defaultProvince',
        city: 'defaultCity',
        url: 'http://default.url',
      },
      publish_time: '2024-01-01T00:00:00Z',
      weather: {
        temperature: 0,
        temperatureDiff: 0,
        airpressure: 1013,
        humidity: 50,
        rain: 0,
        rcomfort: 0,
        icomfort: 0,
        info: 'Clear',
        img: '01',
        feelst: 20,
      },
      wind: {
        direct: 'North',
        degree: 0,
        power: '1级',
        speed: 0,
      },
      warn: {
        alert: 'No warnings',
        pic: '',
        province: '',
        city: '',
        url: '',
        issuecontent: '',
        fmeans: '',
        signaltype: '',
        signallevel: '',
        pic2: '',
      },
      sunriseSunset: {
        sunrise: '06:00',
        sunset: '18:00',
      },
    },
    predict: {
      station: {
        code: 'defaultCode',
        province: 'defaultProvince',
        city: 'defaultCity',
        url: 'http://default.url',
      },
      publish_time: '2024-01-01T00:00:00Z',
      detail: [],
    },
    air: {
      forecasttime: '2024-12-19 15:00',
      aqi: 91,
      aq: 2,
      text: '良',
      aqiCode: '99031;99032;99033;99035;99037;99038;99039;99040',
    },
    tempchart: [],
    passedchart: [],
    climate: {
      time: '',
      month: [],
    },
    radar: {
      title: '实时雷达数据',
      image: '',
      url: '',
    },
  }
}

async function getData() {
  try {
    if (!province.value || !city.value) {
      return
    }

    clearData()

    isLoading.value = true

    const response = await AdminApi.getWeather(city.value)

    data.value = response
  }
  catch (error: any) {
    window.$notification?.error({
      title: '获取数据失败，请稍后重试',
      message: error.message,
    })
    clearData()
  }
  finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  await getData()
})

const options = provinceCityData.map((item) => {
  return {
    value: item.code,
    label: item.name,
    children: item.children.map(city => ({
      value: city.code,
      label: city.city,
    })),
  }
})

const value = ref(['AHN', 'zOenJ'])

const props = {
  expandTrigger: 'hover' as const,
}

async function handleChange(value: CascaderValue) {
  // 首先确保 value 是一个数组（非多选情况下）
  if (!Array.isArray(value)) {
    console.error('Cascader value should be an array in single-select mode')
    return
  }

  // 使用类型断言明确 value 是 string[] 或 number[]
  const selectedValues = value as string []

  // 提供默认值防止 undefined 访问
  province.value = selectedValues[0] ?? ''
  city.value = selectedValues[1] ?? ''

  await getData()
}

const activeTab = ref('realtime')
</script>

<template>
  <div
    class="h-full w-full flex flex-col"
  >
    <div
      class="flex items-center gap-5"
    >
      <el-cascader
        v-model="value"
        :options="options"
        :props="props"
        size="large"
        @change="handleChange"
      />

      <div
        v-if="data.real && data.real.publish_time"
        class="m-l-10"
      >
        数据为
        <span
          class="color-red"
        >
          {{ data.real.publish_time.slice(-5) }}
        </span>
        更新
      </div>
    </div>

    <div
      v-loading="isLoading"
      class="flex flex-col flex-1"
    >

      <Meter
        v-if="data.tempchart.length && !isLoading"
        v-model="data"
      />

      <el-tabs
        class="w-full"
      >
        <el-tab-pane
          label="预报数据"
        >
          <div
            class="h-[500px]"
          >
            <TempChart
              v-if="data.tempchart.length"
              v-model="data"
            />
          </div>
        </el-tab-pane>

        <el-tab-pane
          label="24小时实时天气"
          lazy
        >
          <div
            class="h-[500px]"
          >
            <PassedChart
              v-if="activeTab === 'realtime' && data.passedchart.length"
              v-model="data"
            />
          </div>
        </el-tab-pane>
      </el-tabs>

      <el-divider />

      <Climate
        v-if="data.tempchart.length"
        v-model="data"
      />
    </div>
  </div>
</template>

<style lang="scss" scoped>
// :deep(.el-cascader-menu__wrap.el-scrollbar__wrap) {
//   height: 300px !important;
// }
</style>

// src/pages/blog/news/weather/index.tsx
import { Select, Spin } from "antd";
import { useState, useEffect, useCallback } from "react";
import { provinceCityData } from "./data";
import { BlogApi } from "@/api";
import { toast } from "sonner";
import Card from "@/components/card";
import Climate from "./components/climate";
import PassedChart from "./components/passedChart";
import Tempchart from "./components/tempchart";
import Meter from "./components/meter";
import type { WeatherType } from "./type";
import { Tabs } from "antd";

/**
 *  省份选择框的选项
 */
const provinceSelectOptions = provinceCityData.map((region) => ({
	value: region.code,
	label: region.name,
}));

/**
 *  根据省份获取对应城市选项
 */
const citySelectOptions = provinceCityData.reduce(
	(acc, region) => {
		acc[region.code] = region.children.map((city) => ({
			value: city.code,
			label: city.city,
		}));
		return acc;
	},
	{} as Record<string, { value: string; label: string }[]>,
);

function Weather() {
	const [loading, setLoading] = useState(false);

	const [data, setData] = useState<WeatherType>({
		real: {
			station: {
				code: "defaultCode",
				province: "defaultProvince",
				city: "defaultCity",
				url: "http://default.url",
			},
			publish_time: "2024-01-01T00:00:00Z",
			weather: {
				temperature: 0,
				temperatureDiff: 0,
				airpressure: 1013,
				humidity: 50,
				rain: 0,
				rcomfort: 0,
				icomfort: 0,
				info: "Clear",
				img: "01",
				feelst: 20,
			},
			wind: {
				direct: "North",
				degree: 0,
				power: "1级",
				speed: 0,
			},
			warn: {
				alert: "No warnings",
				pic: "",
				province: "",
				city: "",
				url: "",
				issuecontent: "",
				fmeans: "",
				signaltype: "",
				signallevel: "",
				pic2: "",
			},
			sunriseSunset: {
				sunrise: "06:00",
				sunset: "18:00",
			},
		},
		predict: {
			station: {
				code: "defaultCode",
				province: "defaultProvince",
				city: "defaultCity",
				url: "http://default.url",
			},
			publish_time: "2024-01-01T00:00:00Z",
			detail: [
				{
					date: "",
					pt: "",
					day: {
						weather: {
							info: "Clear",
							img: "01",
							temperature: "20",
						},
						wind: {
							direct: "North",
							power: "1级",
						},
					},
					night: {
						weather: {
							info: "Clear",
							img: "01",
							temperature: "15",
						},
						wind: {
							direct: "North",
							power: "1级",
						},
					},
					precipitation: 0,
				},
			],
		},
		air: {
			forecasttime: "2024-12-19 15:00",
			aqi: 91,
			aq: 2,
			text: "良",
			aqiCode: "99031;99032;99033;99035;99037;99038;99039;99040",
		},
		tempchart: [
			{
				time: "2024-01-01T12:00:00Z",
				max_temp: 25,
				min_temp: 18,
				day_img: "01",
				day_text: "Clear",
				night_img: "01",
				night_text: "Clear",
			},
		],
		passedchart: [
			{
				rain1h: 0,
				rain6h: 0,
				rain12h: 0,
				rain24h: 0,
				temperature: 20,
				tempDiff: "",
				humidity: 50,
				pressure: 1013,
				windDirection: 0,
				windSpeed: 0,
				time: "2024-01-01T00:00:00Z",
			},
		],
		climate: {
			time: "",
			month: [
				{
					month: 1,
					maxTemp: 25,
					minTemp: 18,
					precipitation: 0,
				},
				{
					month: 2,
					maxTemp: 25,
					minTemp: 18,
					precipitation: 0,
				},
			],
		},
		radar: {
			title: "实时雷达数据",
			image: "",
			url: "",
		},
	});

	const [state, setState] = useState({
		province: "AHN",
		city: "pwvLl",
	});

	const [citiesForSelectedProvince, setCitiesForSelectedProvince] = useState<
		{
			value: string;
			label: string;
		}[]
	>(citySelectOptions[state.province] || []);

	// 初始化默认省份和城市
	useEffect(() => {
		setCitiesForSelectedProvince(citySelectOptions[state.province]);
	}, [state.province]);

	/**
	 *  获取数据逻辑
	 */
	const getData = useCallback(async () => {
		try {
			setLoading(true);

			const response = await BlogApi.getWeather(state.city);

			setData(response);
		} catch (error) {
			toast.error(error.message || "获取数据失败，请稍后重试");
		} finally {
			setLoading(false);
		}
	}, [state.city]);

	useEffect(() => {
		getData();
	}, [getData]);

	return (
		<Card className="flex flex-col gap-5 h-auto">
			<div className="flex gap-5 flex-wrap w-full items-center">
				{/* 省份选择框 */}
				<Select
					className="!w-44"
					showSearch
					placeholder="请选择省"
					value={state.province}
					onChange={(province) => {
						const firstCity = citySelectOptions[province]?.[0]?.value || "";
						setState({
							province,
							city: firstCity,
						});
					}}
					options={provinceSelectOptions}
				/>

				{/* 城市选择框 */}
				<Select
					className="!w-44"
					showSearch
					placeholder="请选择市"
					value={state.city}
					onChange={(city) => setState((prevState) => ({ ...prevState, city }))}
					options={citiesForSelectedProvince}
					disabled={!state.province} // 禁用逻辑
				/>

				{data.real.publish_time && (
					<div className="">{data.real.publish_time.slice(-5)} 更新</div>
				)}
			</div>

			<div className="relative w-full">
				{loading && (
					<Spin
						size="large"
						className="!absolute z-10 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2"
					/>
				)}

				<Meter data={data} />

				<Tabs
					className="w-full !h-[550px]"
					defaultActiveKey="1"
					items={[
						{
							key: "1",
							label: "预报数据",
							children: <Tempchart data={data} />,
						},
						{
							key: "2",
							label: "24小时实时天气",
							children: <PassedChart data={data} />,
						},
					]}
				/>
				{data.climate && <Climate data={data} />}
			</div>
		</Card>
	);
}

export default Weather;
