// src/layouts/home/header/index.tsx
import DesktopMenu from "./components/desktop-menu";
import MobileMenu from "./components/mobile-menu";

import Logo from "@/components/logo";

import Github from "@/components/github";

const menuList = [
	{
		key: "/home/about",
		label: "About",
	},
	{
		key: "/home/work",
		label: "Work",
	},
	{
		key: "/home/contact",
		label: "Contact",
	},
	{
		key: "/blog",
		label: "Blog",
	},
	{
		key: "/garage",
		label: "Garage",
	},
];

export default function HomeHeader({ headerHeight = 80 }) {
	return (
		<header
			className="flex w-full  justify-center fixed top-0 z-[999] bg-[#191919]"
			style={{ height: `${headerHeight}px` }}
		>
			<div className="container flex items-center justify-between mx-5">
				<Logo />

				<DesktopMenu menuList={menuList} />

				<div className="flex items-center gap-5">
					<Github iconColor="#ffffff" />
					{/* 下拉菜单,只有h5可见 */}
					<MobileMenu menuList={menuList} headerHeight={headerHeight} />
				</div>
			</div>
		</header>
	);
}

// src/layout/home-layout/components/header/index.vue
<script lang="ts" setup>
import MobileMenu from './components/mobile-menu.vue'

import PcMenu from './components/pc-menu.vue'

const menuList = [
  {
    key: '/home/about',
    label: 'About',
  },
  {
    key: '/home/work',
    label: 'Work',
  },
  {
    key: '/home/contact',
    label: 'Contact',
  },
  {
    key: '/blog',
    label: 'Blog',
  },
  {
    key: '/command',
    label: 'Command',
  },
  {
    key: '/garage',
    label: 'Garage',
  },
]
</script>

<template>
  <nav
    class="fixed left-0 right-0 top-0 z-100 h-20 flex justify-center bg-[#191919]"
  >
    <div
      class="mx-5 flex items-center justify-between container"
    >

      <Logo />

      <PcMenu
        v-if="!isMobile"
        :menu-list="menuList"
      />

      <!-- 右边 -->
      <div
        class="flex items-center gap-5"
      >
        <Github />

        <MobileMenu
          v-if="isMobile"
          :menu-list="menuList"
        />
      </div>
    </div>
  </nav>
</template>

<style lang="less" scoped>

</style>
