// src/pages/blog/socialEngineering/licensePlate/index.vue
<script lang="ts" setup>
import { BlogApi } from '@/api'

import { Notification } from '@arco-design/web-vue'

import { ref } from 'vue'

const isLoading = ref(false)

const licensePlate = ref('京A12345')

const licensePlateData = ref<any>({
})

/**
 *  清空数据
 */
function clearData() {
  licensePlateData.value = {
  }
}

async function getData() {
  try {
    if (!licensePlate.value) {
      throw new Error('请输入车牌')
    }

    clearData()

    isLoading.value = true

    const response = await BlogApi.getLicensePlateNumberInfo(licensePlate.value)

    licensePlateData.value = response
  }
  catch (error: any) {
    Notification.error(error.message || '获取数据失败，请稍后重试')

    clearData()
  }
  finally {
    isLoading.value = false
  }
}

const typeMap: Record<string, string> = {
  10: '民用',
  20: '军用',
  30: '使馆',
  40: '民航',
  50: '武警',
}

onMounted(() => {
  getData()
})
</script>

<template>
  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <div
      class="flex items-center gap-5"
    >
      <a-input-search
        v-model="licensePlate"
        class="w-[60%]"
        allow-clear
        search-button
        placeholder="请输入车牌"
        :loading="isLoading"
        @search="getData"
        @press-enter="getData"
        @clear="clearData"
      >
        <template
          #button-icon
        >
          <SvgIcon
            icon="blog-search"
          />
        </template>

        <template
          #button-default
        >
          搜索
        </template>
      </a-input-search>

    </div>

    <a-spin
      :loading="isLoading"
    >
      <a-descriptions
        :column="{ xs: 1, md: 1, lg: 1 }"
        bordered
      >

        <a-descriptions-item
          :span="1"
          label="省份"
        >
          {{ licensePlateData.province_name }}
        </a-descriptions-item>

        <a-descriptions-item
          :span="1"
          label="城市"
        >
          {{ licensePlateData.city }}
        </a-descriptions-item>

        <a-descriptions-item
          :span="1"
          label="机构名称"
        >
          {{ licensePlateData.organization }}
        </a-descriptions-item>

        <a-descriptions-item
          :span="1"
          label="类型编码"
        >
          <span
            v-if="licensePlateData.type"
          >
            {{ typeMap[licensePlateData.type] }}
          </span>
        </a-descriptions-item>
      </a-descriptions>

    </a-spin>

  </div>
</template>

// src/pages/blog/socialEngineering/licensePlate/index.tsx
import { BlogApi } from "@/api";
import Card from "@/components/card";
import { isValidPlateNumber } from "@/utils";
import { useThrottleFn } from "ahooks";
import { Descriptions, Input, Spin } from "antd";
import { useState } from "react";
import { toast } from "sonner";

const typeMap: Record<string, string> = {
	"10": "民用",
	"20": "军用",
	"30": "使馆",
	"40": "民航",
	"50": "武警",
};

/**
 *  表示车牌信息的数据结构
 */
type PlateInfoType = {
	/**
	 *  省份
	 */
	province_name: string;
	/**
	 *  城市
	 */
	city: string;

	/**
	 *  组织
	 */
	organization: string;

	/**
	 *  类型
	 */
	type: string | number;
};

function LicensePlate() {
	const [loading, setLoading] = useState(false);

	const [error, setError] = useState("");

	//  京A12345
	const [keyword, setKeyword] = useState("京A12345");

	const [data, setData] = useState<PlateInfoType>({
		province_name: "",
		city: "",
		organization: "",
		type: "",
	});

	const items = [
		{
			label: "省份",
			children: data.province_name || "无",
			span: 3,
		},
		{
			label: "城市",
			children: data.city || "无",
			span: 3,
		},
		{
			label: "机构名称",
			children: data.organization || "无",
			span: 3,
		},
		{
			label: "类型编码",
			children: data.type ? <span>{typeMap[data.type]}</span> : "无",
			span: 3,
		},
	];

	/**
	 * 检查并获取车牌数据
	 */
	async function getData() {
		try {
			if (!keyword) {
				throw new Error("请输入车牌号");
			}

			if (!isValidPlateNumber(keyword)) throw new Error("请输入有效的车牌号");

			setLoading(true);

			const response = await BlogApi.getLicensePlateNumberInfo(keyword);

			setData(response);
		} catch (error: any) {
			toast.error(error.message || "获取数据失败，请稍后重试");
			setError(error.message);
		} finally {
			setLoading(false);
		}
	}

	/**
	 *  使用 ahooks 的节流
	 */
	const { run: throttledGetData } = useThrottleFn(
		() => {
			getData();
		},
		{
			wait: 1000,
			leading: false,
		},
	);

	/**
	 * 输入变化的处理
	 */
	function handleInputChange(e: React.ChangeEvent<HTMLInputElement>) {
		setKeyword(e.target.value.trim());
		setError("");
	}

	/**
	 *  搜索
	 */
	function handleInputSearch(info?: { source?: "input" | "clear" }) {
		if (info && info.source === "clear") {
			setKeyword("");

			setError("");

			setData({
				province_name: "",
				city: "",
				organization: "",
				type: "",
			});
			return;
		}

		throttledGetData();
	}

	return (
		<Card className="flex flex-col gap-5">
			<div className="flex gap-5 flex-wrap w-full items-center">
				<Input.Search
					className="!w-80"
					loading={loading}
					disabled={loading}
					value={keyword}
					onChange={handleInputChange}
					onSearch={(_, __, info) => handleInputSearch(info)}
					placeholder="请输入车牌号"
					allowClear
					status={error ? "error" : ""}
					enterButton="搜索"
				/>

				<div className="flex items-center">
					{error && <span className="text-red ">{error}</span>}
				</div>
			</div>

			<div className="relative w-full">
				{loading && (
					<Spin
						size="large"
						className="!absolute z-10 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2"
					/>
				)}

				<Descriptions
					labelStyle={{
						width: 160,
					}}
					bordered
					items={items}
				/>
			</div>
		</Card>
	);
}

export default LicensePlate;
