// src/pages/老博客/news/price/cigarette/index.vue
<script lang="ts" setup>
import { BlogApi } from '@/api'

import { Notification } from '@arco-design/web-vue'

import { ref } from 'vue'

const isLoading = ref(false)

const cigaretteName = ref('白沙')

const cigaretteData = ref<any>([])

/**
 *  清空数据
 */
function clearData() {
  cigaretteData.value = []
}

async function getData() {
  try {
    if (!cigaretteName.value) {
      throw new Error('请输入香烟名称')
    }

    clearData()

    isLoading.value = true

    const response = await BlogApi.getCigarettePrice(cigaretteName.value)

    cigaretteData.value = response
  }
  catch (error: any) {
    Notification.error(error.message || '获取数据失败，请稍后重试')

    clearData()
  }
  finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  await getData()
})
</script>

<template>
  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <div
      class="flex items-center gap-5"
    >
      <a-input-search
        v-model="cigaretteName"
        class="w-[60%]"
        allow-clear
        search-button
        placeholder="请输入香烟名称"
        :loading="isLoading"
        @search="getData"
        @press-enter="getData"
        @clear="clearData"
      >
        <template
          #button-icon
        >
          <SvgIcon
            icon="blog-search"
          />
        </template>

        <template
          #button-default
        >
          香烟搜索
        </template>
      </a-input-search>
    </div>

    <a-table
      :data="cigaretteData"
      :loading="isLoading"
      scrollbar
      :scroll="{
        maxHeight: 'calc(100vh - 300px)',
      }"
      :pagination="false"
    >
      <template
        #columns
      >
        <a-table-column
          title="ID"
          data-index="id"
          align="center"
          :width="100"
        />

        <a-table-column
          title="香烟名称"
          data-index="name"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
        />

        <a-table-column
          title="单盒参考价"
          data-index="单盒参考价"
          align="center"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
        />

        <a-table-column
          title="条盒参考价"
          data-index="条盒参考价"
          align="center"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
        />

        <a-table-column
          title="香烟类型"
          data-index="香烟类型"
          align="center"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
        />

        <a-table-column
          title="烟碱量"
          data-index="烟碱量"
          align="center"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
        />

        <a-table-column
          title="焦油量"
          data-index="焦油量"
          align="center"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
        />

        <a-table-column
          title="烟支规格"
          data-index="烟支规格"
          align="center"
          :sortable="{
            sortDirections: ['ascend', 'descend'],
          }"
          :width="240"
        />
      </template>
    </a-table>
  </div>
</template>

<style lang="less" scoped>
:deep(.arco-card-body) {
  height: calc(100% - 60px);
}
</style>

// src/pages/blog/price/cigarette/index.tsx
import { BlogApi } from "@/api";
import Card from "@/components/card";
import { useThrottleFn } from "ahooks";
import { Input, Table } from "antd";
import { useState } from "react";
import { toast } from "sonner";

const columns = [
	{
		title: "香烟",
		dataIndex: "name", // 数据字段名
		key: "name",
	},
	{
		title: "单盒参考价",
		dataIndex: "单盒参考价",
		key: "singleBoxPrice",
	},
	{
		title: "条盒参考价",
		dataIndex: "条盒参考价",
		key: "boxPrice",
	},
	{
		title: "条盒批发价",
		dataIndex: "条盒批发价",
		key: "wholesalePrice",
	},
	{
		title: "香烟类型",
		dataIndex: "香烟类型",
		key: "type",
	},
	{
		title: "焦油量",
		dataIndex: "焦油量",
		key: "tarAmount",
	},
	{
		title: "烟碱量",
		dataIndex: "烟碱量",
		key: "nicotineAmount",
	},
	{
		title: "包装形式",
		dataIndex: "包装形式",
		key: "packaging",
	},
	{
		title: "烟支规格",
		dataIndex: "烟支规格",
		key: "cigaretteSpecs",
	},
];

function Cigarette() {
	const [loading, setLoading] = useState(false);

	const [data, setData] = useState([]);

	const [error, setError] = useState("");

	const [keyword, setKeyword] = useState("白沙");

	/**
	 *  获取数据逻辑
	 */
	async function getData() {
		try {
			if (!keyword) {
				throw new Error("请输入香烟名称");
			}

			setLoading(true);

			const response = await BlogApi.getCigarettePrice(keyword);

			setData(response as any);
		} catch (error) {
			toast.error(error.message || "获取数据失败，请稍后重试");
			setError(error.message || "获取数据失败，请稍后重试");
		} finally {
			setLoading(false);
		}
	}
	/**
	 *  使用 ahooks 的节流
	 */
	const { run: throttledGetData } = useThrottleFn(
		() => {
			getData();
		},
		{
			wait: 1000,
			leading: false,
		},
	);

	function handleInputChange(e: any) {
		setKeyword(e.target.value.trim());
		if (error) {
			setError("");
		}
	}

	/**
	 *  搜索
	 */
	function handleInputSearch(info?: { source?: "input" | "clear" }) {
		if (info && info.source === "clear") {
			setKeyword("");

			setError("");

			setData([]);

			return;
		}

		throttledGetData();
	}
	return (
		<Card className="flex flex-col gap-5">
			<div className="flex gap-5 flex-wrap w-full items-center">
				<Input.Search
					className="!w-80"
					loading={loading}
					disabled={loading}
					value={keyword}
					onChange={handleInputChange}
					onSearch={(_, __, info) => handleInputSearch(info)}
					placeholder="请输入香烟名称"
					allowClear
					status={error ? "error" : ""}
					enterButton="搜索"
				/>

				<div className="flex items-center">
					{error && <span className="text-red ">{error}</span>}
				</div>
			</div>

			<Table
				columns={columns}
				dataSource={data}
				rowKey="name"
				loading={loading}
				pagination={false}
				scroll={{ y: "calc(100vh - 300px)" }}
			/>
		</Card>
	);
}

export default Cigarette;
