// src/pages/admin/news/price/cigarette/index.vue
<script lang="ts" setup>
import { ref } from 'vue'

import { AdminApi } from '@/apis'

const isLoading = ref(false)

const cigaretteName = ref('白沙')

const cigaretteData = ref<any>([])

/**
 *  清空数据
 */
function clearData() {
  cigaretteData.value = []
}

async function getData() {
  try {
    if (!cigaretteName.value) {
      throw new Error('请输入香烟名称')
    }

    clearData()

    isLoading.value = true

    const response = await AdminApi.getCigarettePrice(cigaretteName.value)

    cigaretteData.value = response
  }
  catch (error: any) {
    window.$notification?.error({
      title: '获取数据失败，请稍后重试',
      message: error.message,
    })
    clearData()
  }
  finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  await getData()
})
</script>

<template>
  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <div
      class="flex items-center gap-5"
    >
      <el-input
        v-model.trim="cigaretteName"
        clearable
        size="large"
        placeholder="请输入香烟名称"
        class="!max-w-[30%] !overflow-hidden"
        @keydown.enter.prevent="getData"
        @clear="clearData"
      >
        <template
          #append
        >
          <BaseButton
            icon="search"
            :loading="isLoading"
            @click="getData"
          />
        </template>
      </el-input>
    </div>

    <div
      v-loading="isLoading"
      class="h-[calc(100vh-200px)]"
    >
      <el-table
        class="!w-full"
        :data="cigaretteData"
        height="100%"
      >

        <el-table-column
          prop="id"
          label="ID"
          align="center"
        />

        <el-table-column
          prop="name"
          label="香烟名称"
          align="center"
          sortable
        />

        <el-table-column
          prop="单盒参考价"
          label="单盒参考价"
          align="center"
          sortable
        />

        <el-table-column
          prop="条盒参考价"
          label="条盒参考价"
          align="center"
          sortable
        />

        <el-table-column
          prop="香烟类型"
          label="香烟类型"
          align="center"
          sortable
        />

        <el-table-column
          prop="烟碱量"
          label="烟碱量"
          align="center"
          sortable
        />

        <el-table-column
          prop="焦油量"
          label="焦油量"
          align="center"
          sortable
        />

        <el-table-column
          prop="烟支规格"
          label="烟支规格"
          align="center"
          sortable
        />

      </el-table>
    </div>
  </div>
</template>

// src/pages/blog/price/cigarette/index.tsx
import { BlogApi } from "@/api";
import Card from "@/components/card";
import { useThrottleFn } from "ahooks";
import { Input, Table } from "antd";
import { useState } from "react";
import { toast } from "sonner";

const columns = [
	{
		title: "香烟",
		dataIndex: "name", // 数据字段名
		key: "name",
	},
	{
		title: "单盒参考价",
		dataIndex: "单盒参考价",
		key: "singleBoxPrice",
	},
	{
		title: "条盒参考价",
		dataIndex: "条盒参考价",
		key: "boxPrice",
	},
	{
		title: "条盒批发价",
		dataIndex: "条盒批发价",
		key: "wholesalePrice",
	},
	{
		title: "香烟类型",
		dataIndex: "香烟类型",
		key: "type",
	},
	{
		title: "焦油量",
		dataIndex: "焦油量",
		key: "tarAmount",
	},
	{
		title: "烟碱量",
		dataIndex: "烟碱量",
		key: "nicotineAmount",
	},
	{
		title: "包装形式",
		dataIndex: "包装形式",
		key: "packaging",
	},
	{
		title: "烟支规格",
		dataIndex: "烟支规格",
		key: "cigaretteSpecs",
	},
];

function Cigarette() {
	const [loading, setLoading] = useState(false);

	const [data, setData] = useState([]);

	const [error, setError] = useState("");

	const [keyword, setKeyword] = useState("白沙");

	/**
	 *  获取数据逻辑
	 */
	async function getData() {
		try {
			if (!keyword) {
				throw new Error("请输入香烟名称");
			}

			setLoading(true);

			const response = await BlogApi.getCigarettePrice(keyword);

			setData(response as any);
		} catch (error) {
			toast.error(error.message || "获取数据失败，请稍后重试");
			setError(error.message || "获取数据失败，请稍后重试");
		} finally {
			setLoading(false);
		}
	}
	/**
	 *  使用 ahooks 的节流
	 */
	const { run: throttledGetData } = useThrottleFn(
		() => {
			getData();
		},
		{
			wait: 1000,
			leading: false,
		},
	);

	function handleInputChange(e: any) {
		setKeyword(e.target.value.trim());
		if (error) {
			setError("");
		}
	}

	/**
	 *  搜索
	 */
	function handleInputSearch(info?: { source?: "input" | "clear" }) {
		if (info && info.source === "clear") {
			setKeyword("");

			setError("");

			setData([]);

			return;
		}

		throttledGetData();
	}
	return (
		<Card className="flex flex-col gap-5">
			<div className="flex gap-5 flex-wrap w-full items-center">
				<Input.Search
					className="!w-80"
					loading={loading}
					disabled={loading}
					value={keyword}
					onChange={handleInputChange}
					onSearch={(_, __, info) => handleInputSearch(info)}
					placeholder="请输入香烟名称"
					allowClear
					status={error ? "error" : ""}
					enterButton="搜索"
				/>

				<div className="flex items-center">
					{error && <span className="text-red ">{error}</span>}
				</div>
			</div>

			<Table
				columns={columns}
				dataSource={data}
				rowKey="name"
				loading={loading}
				pagination={false}
				scroll={{ y: "calc(100vh - 300px)" }}
			/>
		</Card>
	);
}

export default Cigarette;
