// src/pages/admin/media/wallpaper/index.vue
<!------------------------------------    ------------------------------------------------->
<script lang="ts" setup>
import { AdminApi } from '@/apis'

const isLoading = ref(false)

/**
 *  分类
 */
const category = ref('sg')

/**
 *  分类选项
 */
const categoryOptions = [
  {
    value: 'fj',
    label: '风景',
  },
  {
    value: 'yx',
    label: '游戏',
  },
  {
    value: 'mn',
    label: '美女',
  },
  {
    value: 'cy',
    label: '视觉创意',
  },
  {
    value: 'mxys',
    label: '明星影视',
  },
  {
    value: 'qc',
    label: '汽车',
  },
  {
    value: 'dw',
    label: '动物',
  },
  {
    value: 'xqs',
    label: '小清新',
  },
  {
    value: 'ty',
    label: '体育',
  },
  {
    value: 'js',
    label: '军事',
  },
  {
    value: 'dm',
    label: '动漫',
  },
  {
    value: 'qg',
    label: '情感',
  },
  {
    value: 'wz',
    label: '文字',
  },
  {
    value: 'tui',
    label: '腿',
  },
  {
    value: 'sg',
    label: '帅哥',
  },
]

/**
 *  关键字
 */
const wallpaperUrl = ref('')

/**
 * 获取壁纸数据
 */
async function getData() {
  try {
    isLoading.value = true

    if (category.value === 'tui') {
      const response = await AdminApi.getTuiImage()

      wallpaperUrl.value = response.text
    }
    else if (category.value === 'sg') {
      const response = await AdminApi.getRandomManImage()

      wallpaperUrl.value = response.img
    }
    else {
      const response = await AdminApi.getWallpaper(category.value)

      wallpaperUrl.value = response.img_url
    }
  }
  catch (error: any) {
    window.$notification?.error({
      title: '获取数据失败，请稍后重试',
      message: error.message,
    })
  }
  finally {
    isLoading.value = false
  }
}

onMounted(async () => {
  await getData()
})
</script>

<template>
  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <div
      class="flex items-center gap-5"
    >
      <el-select
        v-model="category"
        placeholder="请选择"
        size="large"
        class="!w-60"
        @change="getData"
      >
        <el-option
          v-for="item in categoryOptions"
          :key="item.value"
          :label="item.label"
          :value="item.value"
        />
      </el-select>

      <BaseButton
        tooltip-content="刷新"
        icon="admin-refresh"
        :loading="isLoading"
        @click="getData"
      />

      <DownloadButton
        tooltip-content="下载壁纸"
        :url="wallpaperUrl"
        type="image"
      />
    </div>

    <div
      class="h-[calc(100vh-240px)]"
    >
      <PreviewImg
        :src="wallpaperUrl"
        :loading="isLoading"
      />
    </div>
  </div>
</template>

<style lang="scss" scoped></style>

// src/pages/blog/media/wallpaper/index.tsx
import { BlogApi } from "@/api";
import { useDebounceEffect } from "ahooks";
import { Button, Image, Select, Spin, Tooltip } from "antd";
import { useState } from "react";

import { SvgIcon } from "@/components/icon";

import Card from "@/components/card";
import { downloadImage } from "@/utils/downloadImage";
import { toast } from "sonner";

/**
 * 壁纸组件
 */
function Wallpaper() {
	const [loading, setLoading] = useState(false);

	const [category, setCategory] = useState("mn");

	const [keyword, setKeyword] = useState("");

	/**
	 *  分类选项
	 */
	const categoryOptions = [
		{ value: "fj", label: "风景" },
		{ value: "yx", label: "游戏" },
		{ value: "mn", label: "美女" },
		{ value: "cy", label: "视觉创意" },
		{ value: "mxys", label: "明星影视" },
		{ value: "qc", label: "汽车" },
		{ value: "dw", label: "动物" },
		{ value: "xqs", label: "小清新" },
		{ value: "ty", label: "体育" },
		{ value: "js", label: "军事" },
		{ value: "dm", label: "动漫" },
		{ value: "qg", label: "情感" },
		{ value: "wz", label: "文字" },
		{ value: "tui", label: "腿" },
		{ value: "sg", label: "帅哥" },
	];

	/**
	 * 获取壁纸数据
	 */
	async function getData() {
		try {
			setLoading(true);

			if (category === "tui") {
				const response = await BlogApi.getTuiImage();

				setKeyword(response.text);
			} else if (category === "sg") {
				const response = await BlogApi.getRandomManImage();
				setKeyword(response.img);
			} else {
				const response = await BlogApi.getWallpaper(category);
				setKeyword(response.img_url);
			}
		} catch (error: any) {
			toast.error(error.message || "获取数据失败，请稍后重试");
		} finally {
			setLoading(false);
		}
	}

	/**
	 * 使用 ahooks 的防抖处理输入变化
	 */
	useDebounceEffect(
		() => {
			getData();
		},
		[category],
		{ wait: 500 }, // 防抖时间 500ms
	);
	return (
		<Card className="flex flex-col gap-5">
			<div className="flex gap-5 flex-wrap w-full items-center">
				<Select
					className="w-40"
					showSearch
					placeholder="请选择壁纸类别"
					defaultValue={category}
					onChange={(category) => setCategory(category)}
					options={categoryOptions}
				/>

				<Tooltip placement="top" title="点击刷新">
					<Button
						loading={loading}
						onClick={getData}
						icon={<SvgIcon icon="refresh" />}
					/>
				</Tooltip>

				<Tooltip placement="top" title="点击下载">
					<Button
						onClick={() => downloadImage(keyword)}
						icon={<SvgIcon icon="download" />}
					/>
				</Tooltip>
			</div>

			{/* 壁纸展示区域 */}
			<div className=" flex justify-center items-center bg-gray-200 h-[calc(100vh-240px)] relative">
				{loading && (
					<Spin
						size="large"
						className="!absolute z-10 left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2"
					/>
				)}
				{keyword && (
					<Image src={keyword} alt="壁纸" height="100%" width="auto" />
				)}
			</div>
		</Card>
	);
}

export default Wallpaper;
