// src/pages/code/innovation/calendar/index.vue
<!------------------------------------  日历  ------------------------------------------------->
<script lang="ts" setup>
import type { StateType } from './calendarUtils'

import CalendarUtils from './calendarUtils'

import Left from './left.vue'

import Right from './right.vue'

/**
 *  存储日历的状态，如年份、月份等
 */
const state = ref<StateType>(CalendarUtils.init())

onMounted(() => {
  CalendarUtils.render(state.value)
})

</script>

<template>
  <div
    class="h-full w-full flex items-center justify-center"
  >
    <div
      class="h-full w-full flex items-center justify-between bg-white p-3"
    >

      <Left
        v-model="state"
      />

      <Right
        v-model="state"
      />
    </div>
  </div>
</template>

<style lang="less" scoped>

</style>

// src/pages/blog/creativity/calendar/index.tsx
import { useState } from "react";

import Card from "@/components/card";
import Left from "./left";
import Right from "./right";
import CalendarUtils, { type StateType } from "./utils";

function Calendar() {
	const [state, setState] = useState<StateType>(CalendarUtils.init());

	CalendarUtils.render(state);

	return (
		<Card className="h-full w-full flex items-center justify-center">
			<Left state={state} setState={setState} />
			<Right state={state} setState={setState} />
		</Card>
	);
}

export default Calendar;
