// src/pages/blog/creativity/calendar/left.tsx
import { SvgIcon } from "@/components/icon";
import { useEventListener } from "ahooks";
import type { DatePickerProps } from "antd";
import type React from "react";
import { useEffect, useRef, useState } from "react";
import CalendarUtils from "./utils";
import type { DayType, StateType } from "./utils";

import { Button, DatePicker } from "antd";

import dayjs, { type Dayjs } from "dayjs";
type LeftProps = {
	state: StateType;
	setState: React.Dispatch<React.SetStateAction<StateType>>;
};

function Calendar({ state, setState }: LeftProps) {
	const elementRef = useRef<HTMLDivElement>(null);

	const [monthPicker, setMonthPicker] = useState<Dayjs>(dayjs(new Date()));

	/**
	 * 选择日期
	 */
	const handleSelectDay = (day: DayType): void => {
		const newState = {
			...state,
			selectedDay: {
				...day,
				isSelected: true,
			},
		};

		CalendarUtils.render(newState);
		setState(newState);
	};

	/**
	 * 重置为当前日期
	 */
	const handleToday = (): void => {
		const updatedState = CalendarUtils.init();

		CalendarUtils.render(updatedState);

		setState({
			...updatedState,
		});
	};

	/**
	 * 监听年份、月份变化时调用渲染函数
	 */
	useEffect(() => {
		const newDayjsDate = dayjs(new Date(state.year, state.month - 1, 1));
		setMonthPicker(newDayjsDate);
		setState(state);
	}, [state, setState]);

	/**
	 * 月份选择器变化
	 */
	const handleMonthPickerChange: DatePickerProps["onChange"] = (date) => {
		const newState = {
			...state,
			year: date.year(),
			month: date.month() + 1,
			selectedDay: CalendarUtils.init().selectedDay,
		};

		CalendarUtils.render(newState);

		setState(newState);
	};

	/**
	 * 跳转到上一个月
	 */
	function handlePreviousMonth() {
		let newMonth = state.month - 1;
		let newYear = state.year;

		if (newMonth < 1) {
			newMonth = 12;
			newYear -= 1;
		}

		const newState = {
			...state,
			month: newMonth,
			year: newYear,
		};

		CalendarUtils.render(newState);

		setState(newState);
	}

	/**
	 * 跳转到下一个月
	 */
	function handleNextMonth(): void {
		let newMonth = state.month + 1;
		let newYear = state.year;

		if (newMonth > 12) {
			newMonth = 1;
			newYear += 1;
		}

		const newState = {
			...state,
			month: newMonth,
			year: newYear,
		};

		CalendarUtils.render(newState);

		setState(newState);
	}

	/**
	 *  鼠标滚动
	 */
	useEventListener(
		"wheel",
		(event: WheelEvent) => {
			if (event.deltaY < 0) {
				handlePreviousMonth();
			} else {
				handleNextMonth();
			}
		},
		{ target: elementRef },
	);
	return (
		<div className="h-full w-2/3 flex flex-col p-5">
			{/* 日期选择和按钮行 */}
			<div className="h-10 flex items-center">
				<DatePicker
					value={monthPicker}
					format={"YYYY/MM"}
					picker="month"
					onChange={handleMonthPickerChange}
				/>

				<Button
					className="ml-3"
					icon={<SvgIcon icon="blog-leftArrow" />}
					onClick={handlePreviousMonth}
				/>

				<Button
					className="ml-3"
					icon={<SvgIcon icon="blog-rightArrow" />}
					onClick={handleNextMonth}
				/>

				{state.isShowBackToday && (
					<Button
						className="ml-3"
						icon={<SvgIcon icon="blog-position" />}
						onClick={handleToday}
					/>
				)}
			</div>

			{/* 日历的星期数组 */}
			<div className="ml-10 flex items-center justify-around">
				{state.monthData.weekTitleArray.map((weekTitle) => (
					<div
						key={weekTitle}
						className={`mx-1 text-center text-2xl ${weekTitle === "六" || weekTitle === "日" ? "text-red" : ""}`}
					>
						{weekTitle}
					</div>
				))}
			</div>

			{/* 背景 */}
			<div ref={elementRef} className="relative flex flex-col flex-1">
				<div className="absolute left-0 top-0 h-full w-full flex items-center justify-center text-[320px] text-[#999] opacity-10">
					{state.month}
				</div>

				{state.monthData.weeks.map((week) => (
					<div
						key={week.weekIndex}
						className="my-1 h-full w-full flex items-center justify-around"
					>
						<div
							className={`w-16 flex items-center justify-start text-xl ${week.isTodayWeek ? "text-primary" : ""}`}
						>
							<span className="font-bold">{week.weekIndex}</span>

							<span>周</span>
						</div>

						{week.dayArray.map((day, dayIndex) => (
							<div
								key={day.day}
								onClick={() => handleSelectDay(day)}
								className={`relative mx-1 h-full flex flex-col flex-1 cursor-pointer items-center justify-center border-4 rounded-2xl
                  ${day.isSelected ? "border-primary" : ""}
                  ${day.isRestDay || dayIndex >= 5 ? "bg-#FBDFDF" : ""}
                  ${day.isToday ? "!bg-primary" : ""}
                `}
							>
								{/* 日期 */}
								<div
									className={`text-2xl font-bold ${day.isToday ? "!text-[#fff]" : ""}`}
								>
									{day.day}
								</div>

								{/* 文字 */}
								<div
									className={`text-center text-4 font-bold leading-4 ${day.isFestival ? "text-[#A38CF3]" : ""}`}
								>
									{day.desc}
								</div>

								{/* 标记 */}
								{day.isHoliday && (
									<div
										className={`absolute right-1 top-1 h-4 w-4 flex items-center justify-center rounded-xl text-xs text-[#fff]
                      ${day.isRestDay ? "bg-red" : "bg-[#333]"}
                    `}
									>
										{day.isRestDay ? "休" : "班"}
									</div>
								)}
							</div>
						))}
					</div>
				))}
			</div>
		</div>
	);
}

export default Calendar;

// src/pages/blog/creativity/calendar/left.vue
<!------------------------------------    ------------------------------------------------->
<script lang="ts" setup>
import type { DayType, StateType } from './utils'

import CalendarUtils from './utils'

const elementRef = ref<HTMLElement | null>(null)

const state = defineModel<StateType>({
  required: true,
})

/**
 *  当前月份,用来给月份选择器绑定
 */
const monthPicker = ref(new Date())

/**
 *  选择日期
 */
function handleSelectDay(day: DayType): void {
  state.value.selectedDay = day

  CalendarUtils.render(state.value)
}

/**
 *  重置为当前日期
 */
function handleToday(): void {
  state.value = CalendarUtils.init()
  CalendarUtils.render(state.value)
}

// 设置监听器，当年份、月份、选中的日期或关注的节日月份变化时调用渲染函数
watchEffect(() => {
  monthPicker.value = new Date(state.value.year, state.value.month - 1, 1)
  CalendarUtils.render(state.value)
})

watch(() => state.value.holidayMonth, (newVal) => {
  const month = Number.parseInt(`${newVal}`, 10)

  if (month > 0) {
    state.value.month = month
    CalendarUtils.render(state.value)
  }
})

/**
 *  月份选择器变化
 */
function handleMonthPickerChange(value: Date): void {
  state.value.year = value.getFullYear()
  state.value.month = value.getMonth() + 1
}

/**
 *  跳转到上一个月
 */
function handlePreviousMonth(): void {
  CalendarUtils.toPrevMonth(state.value)
}

/**
 *  跳转到下一个月
 */
function handleNextMonth(): void {
  CalendarUtils.toNextMonth(state.value)
}

/**
 *  监听鼠标滚动
 */
onMounted(() => {
  if (elementRef.value) {
    useEventListener(elementRef.value, 'wheel', (event: WheelEvent) => {
      if (event.deltaY < 0) {
        CalendarUtils.toPrevMonth(state.value)
      }
      else {
        CalendarUtils.toNextMonth(state.value)
      }
    })
  }
})

</script>

<template>
  <!-- 左边 -->
  <div
    class="h-full w-2/3 flex flex-col p-5"
  >
    <!-- 日期选择和按钮行  -->
    <div
      class="h-10 flex items-center"
    >
      <a-month-picker
        v-model="monthPicker"
        class="m-l-3 w-30"
        size="mini"
        value-format="Date"
        @change="handleMonthPickerChange"
      />

      <a-button
        class="m-l-3"
        size="mini"
        @click="handlePreviousMonth"
      >
        <template
          #icon
        >
          <SvgIcon
            icon="arrow-left"
          />
        </template>
      </a-button>

      <a-button
        class="m-l-3"
        size="mini"
        @click="handleNextMonth"
      >
        <template
          #icon
        >
          <SvgIcon
            icon="arrow-right"
          />
        </template>
      </a-button>

      <a-button
        v-if="state.isShowBackToday"
        class="m-l-3 !bg-primary !color-white"
        size="mini"
        @click="handleToday"
      >
        <template
          #icon
        >
          <SvgIcon
            icon="blog-creativity-position"
          />
        </template>
      </a-button>
    </div>

    <!-- 日历的星期数组 (日、一、二、三、四、五、六) -->
    <div
      class="m-l-10 flex items-center justify-around"
    >
      <div
        v-for="weekTitle in state.monthData.weekTitleArray"
        :key="weekTitle"
        :class="[
          {
            'text-red': weekTitle === '六' || weekTitle === '日',
          },
        ]"
        class="m-x-1 text-center text-6"
      >
        {{ weekTitle }}
      </div>
    </div>

    <div
      ref="elementRef"
      class="relative flex flex-col flex-1"
    >
      <!-- 背景 -->
      <div
        class="absolute left-0 top-0 h-full w-full flex items-center justify-center text-80 text-[#999] opacity-10"
      >
        {{ state.month }}
      </div>

      <div
        v-for="(week) in state.monthData.weeks"
        :key="week.weekIndex"
        class="m-y-1 h-full w-full flex items-center justify-around"
      >
        <div
          class="w-15 flex items-center justify-start text-5"
          :class="{
            'text-primary': week.isTodayWeek,
          }"
        >
          <span
            class="font-bold"
          >

            {{ week.weekIndex }}

          </span>

          <span>周</span>
        </div>

        <div
          v-for="(day, dayIndex) in week.dayArray"
          :key="dayIndex"
          :class="[
            day.isSelected ? 'border-4 border-primary' : '',
            day.isRestDay ? 'bg-[#FBDFDF]' : '',
            dayIndex >= 5 ? 'bg-[#FBDFDF]' : '',
            day.isToday ? '!bg-primary' : '',
          ]"
          class="relative m-x-1 h-full flex flex-col flex-1 cursor-pointer items-center justify-center border-4 border-[#D1D3D7] rounded-4 hover:border-primary"
          @click="handleSelectDay(day)"
        >
          <!-- 日期 -->
          <div
            class="date text-6 font-bold"
            :class="[
              day.isRestDay ? 'text-red' : '',
              dayIndex >= 5 ? 'text-red' : '',
              day.isToday ? '!text-white' : '',
            ]"
          >
            {{ day.day }}
          </div>

          <!-- 文字 -->
          <div
            class="desc text-center text-4 font-bold leading-4"
            :class="[
              day.isFestival ? 'text-violet' : '',
              day.isToday ? '!text-white' : '',
            ]"
          >
            {{ day.desc }}
          </div>

          <!-- 标记 -->
          <div
            v-if="day.isHoliday"
            :class="day.isRestDay ? 'bg-red' : 'bg-[#333]'"
            class="sign red absolute right-1 top-1 h-4 w-4 flex items-center justify-center rounded-1 text-3 text-white"
          >
            {{ day.isRestDay ? '休' : '班' }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="less" scoped>

</style>
