// src/pages/admin/socialEngineering/account/index.vue
<script lang="ts" setup>
import { ref } from 'vue'

import { AdminApi } from '@/apis'

const isLoading = ref(false)

const type = ref('qq')

const searchValue = ref('5201314')

type DataType = {
  qq?: {

    /**
     * 查询手机号
     */
    phone: {

      /**
       * QQ号
       */
      qq: string

      /**
       * 手机号
       */
      phone: string

      /**
       * 手机号地区
       */
      phonediqu: string
    }

    /**
     * 查询LOL
     */
    lol: {

      /**
       * LOL名称
       */
      name: string

      /**
       * LOL所在大区
       */
      daqu: string
    }

    /**
     * 查询QQ老密码
     */
    oldPassword: {

      /**
       * QQ老密码
       */
      qqlm: string
    }
  }

  phone?: {
    qq: {

      /**
       * QQ号
       */
      qq: string

      /**
       * 手机号
       */
      phone: string

      /**
       * 手机号地区
       */
      phonediqu: string
    }

    weiBo: {

      /**
       * 微博ID
       */
      id: string
    }
  }

  lol?: {
    qq: {

      /**
       * QQ号
       */
      qq: string

      /**
       * LOL名称
       */
      name: string

      /**
       * LOL所在大区
       */
      daqu: string
    }
  }

  weiBo?: {
    phone: {

      /**
       * 手机号
       */
      phone: string

      /**
       * 手机号地区
       */
      phonediqu: string
    }
  }
}

const data = ref<DataType>({
  qq: {
    phone: {
      qq: '',
      phone: '',
      phonediqu: '',
    },
    lol: {
      name: '',
      daqu: '',
    },
    oldPassword: {
      qqlm: '',
    },
  },
  phone: {
    qq: {
      qq: '',
      phone: '',
      phonediqu: '',
    },
    weiBo: {
      id: '',
    },
  },
  lol: {
    qq: {
      qq: '',
      name: '',
      daqu: '',
    },
  },
  weiBo: {
    phone: {
      phone: '',
      phonediqu: '',
    },
  },
})

/**
 *  清空数据
 */
function clearData() {
  data.value = {
    qq: {
      phone: {
        qq: '',
        phone: '',
        phonediqu: '',
      },
      lol: {
        name: '',
        daqu: '',
      },
      oldPassword: {
        qqlm: '',
      },
    },
    phone: {
      qq: {
        qq: '',
        phone: '',
        phonediqu: '',
      },
      weiBo: {
        id: '',
      },
    },
    lol: {
      qq: {
        qq: '',
        name: '',
        daqu: '',
      },
    },
    weiBo: {
      phone: {
        phone: '',
        phonediqu: '',
      },
    },
  }
}

async function getData() {
  try {
    if (!type.value || !searchValue.value) {
      // throw new Error('请输入香烟名称')
      window.$notification?.error('请输入!')
      return
    }

    clearData()

    isLoading.value = true

    if (type.value === 'qq') {
      const [res_phone, res_lol, res_oldPassword] = await Promise.all([
        AdminApi.getQqQueryPhone(searchValue.value),

        AdminApi.getQqQueryLol(searchValue.value),

        AdminApi.getQqQueryOldPassword(searchValue.value),
      ])

      data.value = {
        qq: {
          phone: res_phone,
          lol: res_lol,
          oldPassword: res_oldPassword,
        },
      }
    }
    else if (type.value === 'phone') {
      const [res_qq, res_weiBo] = await Promise.all([
        AdminApi.getPhoneQueryQq(searchValue.value),

        AdminApi.getPhoneQueryWeiBo(searchValue.value),
      ])

      data.value = {
        phone: {
          qq: res_qq,
          weiBo: res_weiBo,
        },
      }
    }
    else if (type.value === 'lol') {
      const res_qq = await AdminApi.getLolQueryQq(searchValue.value)

      data.value = {
        lol: {
          qq: res_qq,
        },
      }
    }
    else if (type.value === 'weiBo') {
      const res_phone = await AdminApi.getWeiBoIdQueryPhone(searchValue.value)

      data.value = {
        weiBo: {
          phone: res_phone,
        },
      }
    }
  }
  catch (error: any) {
    window.$notification?.error(error.message || '获取数据失败，请稍后重试')

    clearData()
  }
  finally {
    isLoading.value = false
  }
}

function handleSelectChange() {
  searchValue.value = ''
  clearData()
}

onMounted(async () => {
  await getData()
})
</script>

<template>
  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <div
      class="flex items-center gap-5"
    >

      <el-select
        v-model="type"
        placeholder="请选择"
        size="large"
        class="!w-60"
        @change="handleSelectChange"
      >
        <el-option
          value="qq"
          label="QQ号查询"
        />

        <el-option
          value="phone"
          label="手机号查询"
        />

        <el-option
          value="lol"
          label="LOL查询"
        />

        <el-option
          value="weiBo"
          label="微博ID查询"
        />

      </el-select>

      <el-input
        v-model.trim="searchValue"
        clearable
        size="large"
        :placeholder="
          type === 'qq'
            ? '请输入QQ号'
            : type === 'phone'
              ? '请输入手机号'
              : type === 'lol'
                ? '请输入LOL名称'
                : type === 'weiBo'
                  ? '请输入微博ID'
                  : ''
        "
        class="!max-w-[30%] !overflow-hidden"
        @keydown.enter.prevent="getData"
        @clear="clearData"
      >
        <template
          #append
        >
          <BaseButton
            icon="search"
            :loading="isLoading"
            @click="getData"
          />
        </template>
      </el-input>
    </div>

    <el-descriptions
      v-loading="isLoading"
      :column="1"
      border
    >
      <template
        v-if="type === 'qq'"
      >
        <el-descriptions-item
          :span="1"
          label="手机号"
        >
          {{ data?.qq?.phone.phone }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="手机号归属地"
        >
          {{ data?.qq?.phone.phonediqu }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="LOL名称"
        >
          {{ data?.qq?.lol.name }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="LOL所在大区"
        >
          {{ data?.qq?.lol.daqu }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="QQ老密码"
        >
          {{ data?.qq?.oldPassword.qqlm }}
        </el-descriptions-item>
      </template>

      <template
        v-if="type === 'phone'"
      >
        <el-descriptions-item
          :span="1"
          label="QQ号"
        >
          {{ data?.phone?.qq.qq }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="手机号地区"
        >
          {{ data?.phone?.qq.phonediqu }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="微博ID"
        >
          {{ data?.phone?.weiBo.id }}
        </el-descriptions-item>
      </template>

      <template
        v-if="type === 'lol'"
      >
        <el-descriptions-item
          :span="1"
          label="QQ号"
        >
          {{ data?.lol?.qq.qq }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="手机号地区"
        >
          {{ data?.lol?.qq.name }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="微博ID"
        >
          {{ data?.lol?.qq.daqu }}
        </el-descriptions-item>
      </template>

      <template
        v-if="type === 'weiBo'"
      >
        <el-descriptions-item
          :span="1"
          label="手机号"
        >
          {{ data?.weiBo?.phone.phone }}
        </el-descriptions-item>

        <el-descriptions-item
          :span="1"
          label="手机号地区"
        >
          {{ data?.weiBo?.phone.phonediqu }}
        </el-descriptions-item>
      </template>
    </el-descriptions>
  </div>
</template>

// src/pages/blog/socialEngineering/account/index.tsx
import { BlogApi } from "@/api";
import Card from "@/components/card";
import { isValidQQ } from "@/utils";
import { useThrottleFn } from "ahooks";
import { Descriptions, Input, Select, Spin } from "antd";
import { useState } from "react";
import { toast } from "sonner";

/**
 *  分类
 */
enum Category {
	/**
	 *  QQ号查询
	 */
	QQ = 0,

	/**
	 *  手机号查询
	 */
	PHONE = 1,

	/**
	 *  LOL查询
	 */
	LOL = 2,

	/**
	 *  微博号查询
	 */
	WEIBO = 3,
}

function Account() {
	const [loading, setLoading] = useState(false);

	const [error, setError] = useState("");

	const [data, setData] = useState({
		[Category.QQ]: {
			/**
			 *  查询手机号
			 */
			phone: {
				/**
				 *  QQ号
				 */
				qq: "",

				/**
				 *  手机号
				 */
				phone: "",
				/**
				 *  手机号地区
				 */
				phonediqu: "",
			},

			/**
			 *  查询LOL
			 */
			lol: {
				/**
				 *  LOL名称
				 */
				name: "",
				/**
				 *  LOL所在大区
				 */
				daqu: "",
			},
			/**
			 *  查询QQ老密码
			 */
			oldPassword: {
				/**
				 *  QQ老密码
				 */
				qqlm: "",
			},
		},
		[Category.PHONE]: {
			qq: {
				/**
				 *  QQ号
				 */
				qq: "",

				/**
				 *  手机号
				 */
				phone: "",
				/**
				 *  手机号地区
				 */
				phonediqu: "",
			},
			weiBo: {
				/**
				 *  微博ID
				 */
				id: "",
			},
		},

		[Category.LOL]: {
			qq: {
				/**
				 *  QQ号
				 */
				qq: "",
				/**
				 *  LOL名称
				 */
				name: "",
				/**
				 *  LOL所在大区
				 */
				daqu: "",
			},
		},

		[Category.WEIBO]: {
			phone: {
				phone: "",
				phonediqu: "",
			},
		},
	});

	const items = {
		[Category.QQ]: [
			{
				label: "手机号",
				span: 3,
				children: data[Category.QQ].phone.phone,
			},
			{
				label: "手机号地区",
				span: 3,
				children: data[Category.QQ].phone.phonediqu,
			},
			{
				label: "LOL名称",
				span: 3,
				children: data[Category.QQ].lol.name,
			},
			{
				label: "LOL所在大区",
				span: 3,
				children: data[Category.QQ].lol.daqu,
			},
			{
				label: "QQ老密码",
				span: 3,
				children: data[Category.QQ].oldPassword.qqlm,
			},
		],
		[Category.PHONE]: [
			{
				label: "QQ号",
				span: 3,
				children: data[Category.PHONE].qq.qq,
			},
			{
				label: "手机号地区",
				span: 3,
				children: data[Category.PHONE].qq.phonediqu,
			},
			{
				label: "微博ID",
				span: 3,
				children: data[Category.PHONE].weiBo.id,
			},
		],
		[Category.LOL]: [
			{
				label: "QQ号",
				span: 3,
				children: data[Category.LOL].qq.qq,
			},
			{
				label: "LOL名称",
				span: 3,
				children: data[Category.LOL].qq.name,
			},
			{
				label: "所在大区",
				span: 3,
				children: data[Category.LOL].qq.daqu,
			},
		],
		[Category.WEIBO]: [
			{
				label: "手机号",
				span: 3,
				children: data[Category.WEIBO].phone.phone,
			},
			{
				label: "手机号地区",
				span: 3,
				children: data[Category.WEIBO].phone.phonediqu,
			},
		],
	};

	const [category, setCategory] = useState(Category.QQ);

	const categoryOptions = [
		{ label: "QQ号查询", value: Category.QQ },
		{ label: "手机号查询", value: Category.PHONE },
		{ label: "LOL查询", value: Category.LOL },
		{ label: "微博ID查询", value: Category.WEIBO },
	];
	// 0 : QQ  1:手机号 , 2,lolId 3:weiBoId
	const [inputType, setInputType] = useState<number>(0);

	/**
	 *  选择类别
	 */
	function handleCategoryChange(value: number) {
		setCategory(value);

		// qq号
		if (value === Category.QQ) {
			setInputType(Category.QQ);
		}

		//  手机号
		if (value === Category.PHONE) {
			setInputType(Category.PHONE);
		}

		// lolId
		if (value === Category.LOL) {
			setInputType(Category.LOL);
		}

		// weiBoId
		if (value === Category.WEIBO) {
			setInputType(Category.WEIBO);
		}
	}

	const [qq, setQq] = useState("");

	const [phone, setPhone] = useState("");

	//  中路杀神
	const [lol, setLol] = useState("");

	//  6269902085
	const [weiBoId, setWeiBoId] = useState("");

	/**
	 * 检查并获取车牌数据
	 */
	async function getData() {
		try {
			if (category === Category.QQ && !isValidQQ(qq)) {
				throw new Error("请输入正确的QQ号");
			}

			setLoading(true);

			// QQ号
			if (category === Category.QQ) {
				const res_phone = await BlogApi.getQqQueryPhone(qq);

				const res_lol = await BlogApi.getQqQueryLol(qq);

				const res_oldPassword = await BlogApi.getQqQueryOldPassword(qq);

				setData({
					...data,
					[Category.QQ]: {
						...data[Category.QQ],
						phone: res_phone,
						lol: res_lol,
						oldPassword: res_oldPassword,
					},
				});
			}
			//  手机号
			else if (category === Category.PHONE) {
				const res_qq = await BlogApi.getPhoneQueryQq(phone);
				const res_weiBo = await BlogApi.getPhoneQueryWeiBo(phone);

				setData({
					...data,
					[Category.PHONE]: {
						...data[Category.PHONE],
						qq: res_qq,
						weiBo: res_weiBo,
					},
				});
			}
			//  LOL
			else if (category === Category.LOL) {
				const res_qq = await BlogApi.getLolQueryQq(lol);
				setData({
					...data,
					[Category.LOL]: {
						...data[Category.LOL],
						qq: res_qq,
					},
				});
			}
			//  微博
			else if (category === Category.WEIBO) {
				const res_phone = await BlogApi.getWeiBoIdQueryPhone(weiBoId);
				setData({
					...data,
					[Category.WEIBO]: {
						...data[Category.WEIBO],
						phone: res_phone,
					},
				});
			}
		} catch (error: any) {
			toast.error(error.message || "获取数据失败，请稍后重试");
			setError(error.message);
		} finally {
			setLoading(false);
		}
	}

	/**
	 *  使用 ahooks 的节流
	 */
	const { run: throttledGetData } = useThrottleFn(
		() => {
			getData();
		},
		{
			wait: 1000,
			leading: false,
		},
	);

	function handleInputChange(e: React.ChangeEvent<HTMLInputElement>) {
		if (category === Category.QQ) {
			setQq(e.target.value.trim());
		} else if (category === Category.PHONE) {
			setPhone(e.target.value.trim());
		} else if (category === Category.LOL) {
			setLol(e.target.value.trim());
		} else if (category === Category.WEIBO) {
			setWeiBoId(e.target.value.trim());
		}
		if (error) {
			setError("");
		}
	}

	/**
	 *  搜索
	 */
	function handleInputSearch(info?: { source?: "input" | "clear" }) {
		if (info && info.source === "clear") {
			setQq("");

			setPhone("");

			setLol("");

			setWeiBoId("");

			setError("");

			setData({
				[Category.QQ]: {
					phone: {
						qq: "",

						phone: "",

						phonediqu: "",
					},

					lol: {
						name: "",

						daqu: "",
					},

					oldPassword: {
						qqlm: "",
					},
				},
				[Category.PHONE]: {
					qq: {
						qq: "",

						phone: "",

						phonediqu: "",
					},
					weiBo: {
						id: "",
					},
				},

				[Category.LOL]: {
					qq: {
						qq: "",

						name: "",

						daqu: "",
					},
				},

				[Category.WEIBO]: {
					phone: {
						phone: "",
						phonediqu: "",
					},
				},
			});
			return;
		}

		throttledGetData();
	}
	return (
		<Card className="flex flex-col gap-5">
			<div className="flex gap-5 flex-wrap w-full items-center">
				<Select
					className="w-48"
					showSearch
					placeholder="请选择视频类别"
					value={category}
					onChange={(value) => {
						handleCategoryChange(value);
					}}
					options={categoryOptions}
				/>

				<div className="flex-1 flex items-center gap-2 flex-wrap">
					<>
						{inputType === Category.QQ && (
							<Input.Search
								className="!w-60"
								loading={loading}
								disabled={loading}
								value={qq}
								onChange={handleInputChange}
								onSearch={(_, __, info) => handleInputSearch(info)}
								placeholder="请输入QQ号"
								allowClear
								status={error ? "error" : ""}
								enterButton="搜索"
							/>
						)}

						{inputType === Category.PHONE && (
							<Input.Search
								className="!w-60"
								loading={loading}
								disabled={loading}
								value={phone}
								onChange={handleInputChange}
								onSearch={(_, __, info) => handleInputSearch(info)}
								placeholder="请输入手机号"
								allowClear
								status={error ? "error" : ""}
								enterButton="搜索"
							/>
						)}

						{inputType === Category.LOL && (
							<Input.Search
								className="!w-60"
								loading={loading}
								disabled={loading}
								value={lol}
								onChange={handleInputChange}
								onSearch={(_, __, info) => handleInputSearch(info)}
								placeholder="请输入LOL名称"
								allowClear
								status={error ? "error" : ""}
								enterButton="搜索"
							/>
						)}
						{inputType === Category.WEIBO && (
							<Input.Search
								className="!w-60"
								loading={loading}
								disabled={loading}
								value={weiBoId}
								onChange={handleInputChange}
								onSearch={(_, __, info) => handleInputSearch(info)}
								placeholder="请输入微博ID"
								allowClear
								status={error ? "error" : ""}
								enterButton="搜索"
							/>
						)}
					</>

					<div className="flex items-center">
						{error && <span className="text-red ">{error}</span>}
					</div>
				</div>
			</div>

			<div className="relative w-full">
				{loading && (
					<Spin
						size="large"
						className="!absolute z-10 left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2"
					/>
				)}

				<Descriptions
					labelStyle={{
						width: 160,
					}}
					bordered
					items={items[category]}
				/>
			</div>
		</Card>
	);
}

export default Account;
