// src/pages/code/innovation/time/components/time_four/separator.vue
<script lang="ts" setup>

const props = defineProps({

  /**
   *  @param number
   *    数字
   */
  number: {
    type: Number,
    default: 0,
  },

  /**
   *  颜色
   */
  color: {
    type: String,
    default: '#fff',
  },

})

const refresh = ref<boolean>(true)

watch(
  () => props.number,
  () => {
    refresh.value = !refresh.value
  },
)
</script>

<template>
  <div
    class="flex flex-col justify-around"
  >
    <i
      class="h-2.5 w-2.5 rounded-sm transition-all"
      :style="{
        backgroundColor: color,
        opacity: refresh ? 1 : 0.2,
      }"
    />

    <i
      class="h-2.5 w-2.5 rounded-sm transition-all"
      :style="{
        backgroundColor: color,
        opacity: refresh ? 1 : 0.2,
      }"
    />
  </div>
</template>

// src/pages/blog/creativity/time/components/time_four/separator.tsx
import { useEffect, useState } from "react";

type PropsType = {
	/**
	 * 数字
	 */
	number?: number;

	/**
	 * 颜色
	 */
	color?: string;
};

function DotIndicator({ color = "#04A770" }: PropsType) {
	const [refresh, setRefresh] = useState<boolean>(true);

	// 监听 number 变化，切换 refresh 状态
	useEffect(() => {
		setRefresh((prev) => !prev);
	}, []);

	return (
		<div className="h-24 flex flex-col justify-around">
			<i
				className={"block h-1.5 w-1.5 rounded transition-all"}
				style={{
					opacity: refresh ? 1 : 0.2,
					backgroundColor: color,
				}}
			/>
			<i
				className={"block h-1.5 w-1.5 rounded transition-all"}
				style={{
					opacity: refresh ? 1 : 0.2,
					backgroundColor: color,
				}}
			/>
		</div>
	);
}

export default DotIndicator;
