// src/pages/admin/tool/codec/base64/index.vue
<script lang="ts" setup>

import Modal from './modal.vue'

const isShowModel = ref(false)

const type = ref('code')

const inputText = ref('Hello Word! 代码改变世界！')

const encodedText = ref('')

/**
 *  是否格式错误
 */
const isError = ref<boolean>(false)

function handleSelectChange() {
  inputText.value = ''
}

/**
 *  base64 编码
 */
function base64Encode(str: string): string {
  return btoa(
    encodeURIComponent(str).replace(
      /%([0-9A-F]{2})/g,
      (_, p1) => {
        return String.fromCharCode(Number.parseInt(p1, 16))
      },
    ),
  )
}

/**
 *  base64 解码
 */
function base64Decode(base64Str: string) {
  return decodeURIComponent(
    Array.prototype.map
      .call(atob(base64Str), (c) => {
        return `%${`00${c.charCodeAt(0).toString(16)}`.slice(-2)}`
      })
      .join(''),
  )
}

watchEffect(() => {
  isError.value = false
  try {
    if (type.value === 'code') {
      encodedText.value = base64Encode(inputText.value)
    }
    else {
      encodedText.value = base64Decode(inputText.value)
    }
  }
  catch {
    encodedText.value = ''
    isError.value = true
  }
})

</script>

<template>

  <div
    class="h-full w-full flex flex-col gap-5 overflow-hidden"
  >
    <Modal
      v-if="isShowModel"
      v-model="isShowModel"
    />

    <div
      class="flex items-center justify-between"
    >

      <div
        class="flex items-center gap-5"
      >

        <el-radio-group
          v-model="type"
          @change="handleSelectChange"
        >
          <el-radio-button
            value="code"
            label="Base64-编码"
          />

          <el-radio-button
            value="doCode"
            label="Base64-解码"
          />

        </el-radio-group>

        <el-button
          type="primary"
          plain
          @click="isShowModel = true"
        >
          Base64编码对照表
        </el-button>
      </div>

      <BaseButton
        v-if="!isError && encodedText.length > 0"
        v-copy="{
          text: encodedText,
          message: `${type === 'code' ? 'Base64 编码结果' : 'Base64 解码结果'} 已经复制到剪切板`,
        }"
        :size="40"
        icon="copy"
        tooltip-content="点击复制"
      />
    </div>

    <div
      class="h-[calc(100vh-200px)] flex items-center justify-center gap-15"
    >
      <el-input
        v-model="inputText"
        type="textarea"
        placeholder="请输入 base64 数据"
        class="!h-full !flex-1"
        :input-style="{ height: '100%' }"
        clearable
      />

      <div
        class="h-full flex flex-1 items-center justify-center rounded-2 bg-white !relative"
      >

        <el-alert
          v-if="isError && inputText.length > 0"
          title=" 格式错误，请检查输入"
          type="error"
          class="!w-1/2"
        />

        <div
          v-else
          class="overflow-y-auto break-words break-all border rounded-2 bg-white p-3 !h-full !w-full"
        >
          {{ encodedText }}

        </div>

      </div>
    </div>

  </div>
</template>

// src/pages/blog/tool/codec/base64/index.tsx
import { Input, Select, Button } from "antd";

import { useState, useEffect } from "react";

import Card from "@/components/card";

import Base64TableModal from "./components/base64TableModal";

const { TextArea } = Input;

/**
 * 壁纸组件
 */
function Morse() {
	/**
	 *  分类选项
	 */
	const categoryOptions = [
		{ value: 0, label: "Base64-编码" },
		{ value: 1, label: "Base64-解码" },
	];

	const [category, setCategory] = useState(0);

	const [error, setError] = useState("");

	const [isModalOpen, setIsModalOpen] = useState(false);

	const [keywordOne, setKeywordOne] = useState("Hello Word! 代码改变世界！");

	const [keywordTwo, setKeywordTwo] = useState("");

	const [keywordThree, setKeywordThree] = useState(
		"SGVsbG8gV29yZCEg5Luj56CB5pS55Y+Y5LiW55WM77yB",
	);
	const [keywordFour, setKeywordFour] = useState("");

	// 新增的逻辑
	useEffect(() => {
		try {
			setError(""); // 清空错误信息
			if (category === 0) {
				// 处理包含中文的字符串，进行Base64编码
				setKeywordTwo(
					btoa(
						encodeURIComponent(keywordOne).replace(
							/%([0-9A-F]{2})/g,
							(_, p1) => {
								return String.fromCharCode(Number.parseInt(p1, 16)); // 替换为 Number.parseInt
							},
						),
					),
				);
			} else {
				// 处理包含中文的字符串，进行Base64解码
				const decodedText = decodeURIComponent(
					Array.prototype.map
						.call(atob(keywordThree), (c) => {
							return `%${`00${c.charCodeAt(0).toString(16)}`.slice(-2)}`;
						})
						.join(""),
				);

				// 验证Base64字符串有效性
				if (keywordThree && !decodedText.trim()) {
					setError("输入的Base64无效，请检查后重试!");
				}
				setKeywordFour(decodedText);
			}
		} catch (err) {
			// 捕获异常，设置错误信息
			setError("解码失败，请检查输入内容！");
		}
	}, [category, keywordOne, keywordThree]);

	function showModal() {
		setIsModalOpen(true);
	}
	return (
		<>
			<Base64TableModal
				isOpen={isModalOpen}
				onClose={() => setIsModalOpen(false)}
			/>

			<Card className="flex flex-col gap-5">
				<div className="flex gap-5 flex-wrap w-full items-center">
					<Select
						className="w-40"
						showSearch
						placeholder="请选择壁纸类别"
						defaultValue={category}
						onChange={(category) => setCategory(category)}
						options={categoryOptions}
					/>

					<Button type="primary" onClick={showModal}>
						Base64编码表
					</Button>

					<div className="flex items-center">
						{error && <span className="text-red ">{error}</span>}
					</div>
				</div>

				<div className="flex flex-col gap-5 h-[calc(100vh-240px)] relative w-full">
					{category === 0 ? (
						<>
							<div className="flex-1">
								<TextArea
									style={{ resize: "none", height: "100%" }}
									placeholder="请输入需要编码的文本"
									allowClear
									value={keywordOne}
									onChange={(e) => setKeywordOne(e.target.value)}
								/>
							</div>

							<div className="flex-1">
								<TextArea
									style={{ resize: "none", height: "100%" }}
									placeholder="编码结果"
									readOnly
									value={keywordTwo}
								/>
							</div>
						</>
					) : (
						<>
							<div className="flex-1">
								<TextArea
									style={{ resize: "none", height: "100%" }}
									placeholder="请输入需要解码的Base64文本"
									allowClear
									value={keywordThree}
									onChange={(e) => setKeywordThree(e.target.value)}
								/>
							</div>

							<div className="flex-1">
								<TextArea
									style={{ resize: "none", height: "100%" }}
									placeholder="解码结果"
									readOnly
									value={keywordFour}
								/>
							</div>
						</>
					)}
				</div>
			</Card>
		</>
	);
}

export default Morse;
