// src/pages/home/about/index.vue
<!------------------------------------    ------------------------------------------------->
<script lang="ts" setup>

import Sun from '@/canvas/sun/index.vue'

// import Desktop from '@/canvas/desktop/index.vue'
import Test from '@/canvas/test/index.vue'

import Info from './components/info.vue'

import Intro from './components/intro.vue'

</script>

<template>
  <div
    class="relative h-full w-full"
  >

    <!-- 第一页 -->
    <div
      class="relative min-h-screen w-full"
    >

      <!-- 太阳 -->
      <div
        className="z-2 absolute right-0 top-20 !w-60  aspect-square sm:flex hidden "
      >
        <Sun />
      </div>

      <!-- 电脑桌模型 -->
      <div
        class="absolute z-1"
      >
        <!-- <Desktop /> -->
        <Test />

      </div>

      <!-- 个人介绍 -->
      <Intro />

    </div>

    <!-- 第二页 -->
    <div
      class="relative mx-auto max-w-7xl min-h-screen"
    >
      >
      <Info />
    </div>
  </div>
</template>

<style lang="less" scoped>

</style>

// src/pages/home/about/index.tsx
import Intro from "./components/intro";

import Desktop from "@/canvas/desktop";

// import BrokenBg from "@/canvas/brokenBg";

// import Stars from "@/canvas/stars";

import Sun from "@/canvas/sun";

import Info from "./components/info";

function About() {
	return (
		<div className="h-full w-full  relative ">
			{/* 第一页 */}
			<div className="min-h-screen w-full  relative">
				{/* 太阳 */}
				<div className="absolute right-0 top-20 w-[20vw] aspect-square sm:flex hidden">
					<Sun />
				</div>

				{/* 个人介绍 */}
				<Intro />

				{/* 桌面模型 */}
				<div className="absolute inset-0 z-1">
					<Desktop />
				</div>

				{/* 背景 */}
				{/* <BrokenBg /> */}
			</div>

			{/* 第二页 */}
			<div className="min-h-screen max-w-7xl mx-auto relative">
				<Info />
			</div>
		</div>
	);
}
export default About;
