// src/pages/contact/index.vue
<script lang="ts" setup>

import Moon from '@/canvas/moon/index.vue'

import { sendContactEmail } from '@/utils'

type FormType = {

  /**
   *  姓名
   */
  name: string

  /**
   *  电子邮件
   */
  email: string

  /**
   *  留言
   */
  message: string
}
const formRef = ref<HTMLFormElement | null>(null)

const form = ref<FormType>({
  name: '',
  email: '',
  message: '',
})

const loading = ref(false)

async function handleSubmit(e: Event) {
  e.preventDefault()
  loading.value = true

  try {
    await sendContactEmail(form.value)

    window.$notification?.success({
      title: '邮件发送成功',
      message: '感谢您的留言😃!',
    })
    formRef.value?.reset()
  }
  catch {
    window.$notification.error('邮件发送失败')

    window.$notification?.error({
      title: '邮件发送失败',
      message: '我没有收到你的信息😢!',
    })
  }
  finally {
    loading.value = false
  }
}
</script>

<template>
  <div
    class="relative mx-auto h-full max-w-7xl w-full px-10 py-40 max-sm:px-5"
  >
    <section
      id="contact"
      class=""
    >
      <p
        class="text-4xl text-primary font-semibold max-sm:text-3xl"
      >
        联系我
      </p>

      <div
        class="grid grid-cols-2 mt-12 w-full gap-5 max-sm:grid-cols-1"
      >
        <!-- 左侧 -->
        <div
          v-light
          class="relative flex flex-col gap-5 rounded-lg p-10 shadow-[#0e0e10] shadow-2xl max-sm:px-5 max-sm:py-10"
        >
          <form
            ref="formRef"
            class="mt-12 flex flex-col space-y-7"
            @submit="handleSubmit"
          >
            <label
              class="space-y-3"
            >
              <span
                class="text-lg text-regular"
              >
                姓名
              </span>

              <input
                v-model="form.name"
                type="text"
                name="name"
                required
                class="min-h-14 w-full rounded-lg bg-[#1c1c21] px-5 py-2 text-lg text-primary shadow-[#0E0E10] shadow-2xl placeholder:text-[#62646c] focus:outline-[#DED9FC]"
                placeholder="例如, 张三"
              >
            </label>

            <label
              class="space-y-3"
            >
              <span
                class="text-lg text-regular"
              >
                电子邮件
              </span>

              <input
                v-model="form.email"
                type="email"
                name="email"
                required
                class="min-h-14 w-full rounded-lg bg-[#1c1c21] px-5 py-2 text-lg text-primary shadow-[#0E0E10] shadow-2xl placeholder:text-[#62646c] focus:outline-[#DED9FC]"
                placeholder="例如, zhangSan@gmail.com"
              >
            </label>

            <label
              class="space-y-3"
            >
              <span
                class="text-lg text-regular"
              >
                您的留言
              </span>

              <textarea
                v-model="form.message"
                name="message"
                required
                rows="5"
                class="min-h-14 w-full rounded-lg bg-[#1c1c21] px-5 py-2 text-lg text-primary shadow-[#0E0E10] shadow-2xl placeholder:text-[#62646c] focus:outline-[#DED9FC]"
                placeholder="分享您的想法或询问..."
              />
            </label>

            <button
              class="flex cursor-pointer items-center justify-center gap-2 rounded-lg bg-[#3a3a49] p-3 text-regular transition-all active:scale-95 hover:bg-opacity-70 !hover:text-primary"
              type="submit"
              :disabled="loading"
            >
              {{ loading ? "发送..." : "发送消息" }}
              <SvgIcon
                icon="arrow-top-right"
                size="18"
              />
            </button>
          </form>
        </div>

        <!-- 右侧 -->
        <div
          class="flex items-center justify-center rounded-lg"
        >
          <div
            class="aspect-square w-full"
          >
            <Moon />
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

// src/pages/home/contact/index.tsx
import { useRef, useState } from "react";
import type { ChangeEvent, FormEvent } from "react";

import { Alert, useAlert } from "./alert"; // 引入 Alert 和 useAlert

import { SvgIcon } from "@/components/icon";

import { sendContactEmail } from "@/utils";

// import Earth from "@/canvas/earth";

import Moon from "@/canvas/moon";

/**
 * 表单数据类型
 */
type FormType = {
	/**
	 *  用户名称
	 */
	name: string;
	/**
	 *  用户邮箱
	 */
	email: string;
	/**
	 *  用户留言
	 */
	message: string;
};

const Contact = () => {
	const formRef = useRef<HTMLFormElement | null>(null);
	const { alert, showAlert, hideAlert } = useAlert(); // 使用 useAlert Hook 获取警告状态

	const [loading, setLoading] = useState<boolean>(false);
	const [form, setForm] = useState<FormType>({
		name: "",
		email: "",
		message: "",
	});

	/**
	 * 处理表单字段变更
	 * @param {ChangeEvent<HTMLInputElement | HTMLTextAreaElement>} e - 输入事件对象
	 */
	const handleChange = (
		e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
	) => {
		const { name, value } = e.target;
		setForm((prevForm) => ({ ...prevForm, [name]: value }));
	};

	/**
	 * 处理表单提交
	 */
	const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		setLoading(true);

		try {
			await sendContactEmail(form);

			showAlert({
				text: "感谢您的留言 😃",
				type: "success",
			});

			setTimeout(() => {
				hideAlert();
				setForm({ name: "", email: "", message: "" });
			}, 3000);
		} catch (error) {
			console.error("邮件发送失败:", error);
			showAlert({
				text: "我没有收到你的信息😢",
				type: "danger",
			});
		} finally {
			setLoading(false);
		}
	};

	return (
		<div className="h-full w-full relative max-w-7xl mx-auto pt-20">
			<section className="sm:px-10 px-5 my-20" id="contact">
				{/* 显示警告组件 */}
				{alert.show && <Alert alert={alert} />}
				<div className="w-full text-[#afb0b6]">
					<p className="sm:text-4xl text-3xl font-semibold text-gray_gradient">
						联系我
					</p>

					<div className="grid lg:grid-cols-2 grid-cols-1 mt-12 gap-5 w-full">
						<div className="flex flex-col gap-5 relative sm:p-10 py-10 px-5 shadow-2xl shadow-[#0e0e10]">
							<form
								ref={formRef}
								onSubmit={handleSubmit}
								className="mt-12 flex flex-col space-y-7"
							>
								<label className="space-y-3">
									<span className="text-lg text-[#afb0b6]">姓名</span>
									<input
										type="text"
										name="name"
										value={form.name}
										onChange={handleChange}
										required
										className="w-full bg-[#1c1c21] px-5 py-2 min-h-14 rounded-lg placeholder:text-[#62646c] text-lg text-[#e4e4e6] shadow-[#0E0E10]shadow-2xl focus:outline-[#DED9FC]"
										placeholder="例如, Alan Mathison Turing"
									/>
								</label>

								<label className="space-y-3">
									<span className="text-lg text-[#afb0b6]">电子邮件</span>
									<input
										type="email"
										name="email"
										value={form.email}
										onChange={handleChange}
										required
										className="w-full bg-[#1c1c21] px-5 py-2 min-h-14 rounded-lg placeholder:text-[#62646c] text-lg text-[#e4e4e6] shadow-[#0E0E10]shadow-2xl focus:outline-[#DED9FC]"
										placeholder="例如, turing@gmail.com"
									/>
								</label>

								<label className="space-y-3">
									<span className="text-lg text-[#afb0b6]">您的留言</span>
									<textarea
										name="message"
										value={form.message}
										onChange={handleChange}
										required
										rows={5}
										className="w-full bg-[#1c1c21] px-5 py-2 min-h-14 rounded-lg placeholder:text-[#62646c] text-lg text-[#e4e4e6] shadow-[#0E0E10]shadow-2xl focus:outline-[#DED9FC]"
										placeholder="分享您的想法或询问..."
									/>
								</label>

								<button
									className="p-3 bg-[#3a3a49] text-white cursor-pointer active:scale-95 transition-all rounded-lg hover:bg-opacity-70 flex items-center justify-center gap-2"
									type="submit"
									disabled={loading}
								>
									{loading ? "发送..." : "发送消息"}
									<SvgIcon icon="arrow-top-right" size={18} />
								</button>
							</form>
						</div>

						<div className="rounded-lg flex justify-center items-center">
							<div className="rounded-3xl w-full  h-fit flex justify-center items-center cursor-pointer">
								<Moon height={400} />
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	);
};

export default Contact;
