// src/layouts/blog/iframe/index.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'

import { useRoute } from 'vue-router'

const route = useRoute()

/**
 *  是否加载完成
 */
const isLoaded = ref(false)

/**
 *  监听 route.meta.iframeUrl 的变化
 */
const iframeUrl = computed(() => (route.meta.iframeUrl as string) ?? '')

function handleClick() {
  if (iframeUrl.value) {
    window.open(iframeUrl.value, '_blank', 'noopener,noreferrer')
  }
  else {
    console.warn('iframeUrl 未找到，请确保 meta 中包含 iframeUrl')
  }
}

onMounted(() => {
  if (!iframeUrl.value) {
    console.warn('iframeUrl 未找到，请确保 meta 中包含 iframeUrl')
  }
})
</script>

<template>
  <div
    className="h-full w-full relative flex flex-col"
  >

    <div
      v-if="!isLoaded"
      class="absolute inset-0 z-10 flex items-center justify-center bg-white"
    >
      <!-- 这里是加载动画的具体内容 -->
      <a-spin
        :size="50"
      />
    </div>

    <div
      class="absolute left-0 top-0 z-10"
    >
      <a-tooltip
        content="在新标签页打开"
        position="top"
      >
        <a-button
          shape="circle"
          class="!bg-white"
          @click="handleClick"
        >

          <SvgIcon
            icon="arrow-top-right"
          />
        </a-button>
      </a-tooltip>
    </div>

    <iframe
      v-if="iframeUrl"
      :src="iframeUrl"
      frameborder="0"
      class="h-full w-full"
      @load="isLoaded = true"
    />

  </div>
</template>

<style scoped>
iframe {
  border: none;
}
</style>

// src/layouts/blog/iframe/index.tsx
import { SvgIcon } from "@/components/icon";
import { Spin } from "antd";
import { Button, Tooltip } from "antd";
import { useState } from "react";
type Props = {
	src: string;
};

export default function BlogIframeLayout({ src = "" }: Props) {
	// 使用 state 来控制 iframe 是否加载完成
	const [isLoading, setIsLoading] = useState(true);

	// 当 iframe 加载完成时，更新 isLoading 状态
	const handleLoad = () => {
		setIsLoading(false);
	};

	return (
		<div className="h-full w-full relative flex flex-col">
			{/* 加载中时显示的 loading 效果 */}
			{isLoading && (
				<div className="absolute inset-0 flex items-center justify-center bg-white z-10">
					{/* <p>Loading...</p> */}
					<Spin size="large" />
				</div>
			)}
			<div className="w-full flex py-2 justify-end">
				<Tooltip placement="leftTop" title="在新标签页打开">
					<Button
						onClick={() => window.open(src, "_blank")}
						icon={<SvgIcon icon="arrow-top-right" />}
					/>
				</Tooltip>
			</div>
			{/* iframe 元素 */}
			<iframe
				src={src}
				title="iframe-page"
				className="flex-1 w-full"
				onLoad={handleLoad} // 监听 iframe 加载完成事件
			/>
		</div>
	);
}
