// src/pages/home/components/info.vue
<!------------------------------------    ------------------------------------------------->
<script setup lang="ts">

import { useRouter } from 'vue-router'

import Earth from '@/canvas/earth/index.vue'

import Keyboard from '@/canvas/keyboard/index.vue'

import Mail from '@/canvas/mail/index.vue'

import Skills from '@/canvas/skills/index.vue'

import { copyText } from '@/utils'

const hasCopied = ref(false)

const router = useRouter()

const contactEmailUrl = import.meta.env.VITE_CONTACT_EMAIL

function handleContactMe() {
  router.push({
    name: 'Contact',
  })
}

function handleCopy() {
  copyText(contactEmailUrl)
  hasCopied.value = true
  window.$notification?.success({
    title: '邮箱复制成功',
    message: contactEmailUrl,
  })

  setTimeout(() => {
    hasCopied.value = false
  }, 2000)
}
</script>

<template>
  <section
    id="info"
  >
    <div
      class="grid grid-cols-3 h-full w-full gap-5"
    >
      <!-- 技术栈 -->
      <div
        class="col-span-2 row-span-3 max-sm:col-span-3"
      >
        <div
          class="h-full w-full flex flex-col gap-5 border border-[#1c1c21] rounded-lg border-solid bg-[#0E0E10] p-7 max-sm:p-4"
        >
          <div
            class="h-[266px] w-full cursor-pointer max-sm:h-fit"
          >
            <Skills />
          </div>

          <div>
            <p
              class="mb-2 text-xl text-regular font-semibold"
            >
              技术栈
            </p>

            <p
              class="text-base"
            >
              我擅长各种语言、框架和工具，它们让我能够构建强大且可扩展的应用程序
            </p>
          </div>
        </div>
      </div>

      <!-- 地球部分 -->
      <div
        class="col-span-1 row-span-4 max-sm:col-span-3"
      >
        <div
          class="h-full w-full flex flex-col gap-5 border border-[#1c1c21] rounded-lg border-solid bg-[#0E0E10] p-7 max-sm:p-4"
        >
          <div
            class="h-[326px] w-full flex items-center justify-center rounded-3xl max-sm:h-fit"
          >
            <Earth
              :height="326"
            />
          </div>

          <div>
            <p
              class="mb-2 text-xl text-regular font-semibold"
            >
              我对时区、通讯和位置非常灵活
            </p>

            <p
              class="text-base"
            >
              我居住在湖南长沙，愿意进行远程工作。
            </p>

            <button
              class="mx-auto mt-10 w-full flex cursor-pointer items-center justify-center gap-4 rounded-md bg-[#1c1c21] p-3 text-white transition-all active:scale-95"
              type="button"
              @click="handleContactMe"
            >
              <span
                class="relative h-3 w-3 flex"
              >
                <span
                  class="absolute h-full w-full inline-flex animate-ping rounded-full bg-[#4ade80] opacity-75"
                />

                <span
                  class="relative h-3 w-3 inline-flex rounded-full bg-[#22c55e]"
                />
              </span>
              联系我
            </button>
          </div>
        </div>
      </div>

      <!-- 编码热情部分 -->
      <div
        class="col-span-2 row-span-3 max-sm:col-span-3"
      >
        <div
          class="h-full w-full flex flex-col gap-5 border border-[#1c1c21] rounded-lg border-solid bg-[#0E0E10] p-7 max-sm:p-4"
        >
          <div
            class="h-[266px] cursor-pointer max-sm:w-full"
          >
            <Keyboard />
          </div>

          <div>
            <p
              class="mb-2 text-xl text-regular font-semibold"
            >
              我对编码的热情
            </p>

            <p
              class="text-base"
            >
              我喜欢通过代码解决问题和构建事物,喜欢探索新技术并提高自己的技能。
            </p>
          </div>
        </div>
      </div>

      <!-- 联系我部分 -->
      <div
        class="col-span-1 row-span-2 max-sm:col-span-3"
      >
        <div
          class="h-full w-full flex flex-col gap-5 border border-[#1c1c21] rounded-lg border-solid bg-[#0E0E10] p-7 max-sm:p-4"
        >
          <div
            class="aspect-square h-[120px] w-full cursor-pointer max-sm:h-fit"
          >
            <Mail />
          </div>

          <button
            class="mx-auto mt-10 w-full flex cursor-pointer items-center justify-center gap-4 rounded-md bg-[#1c1c21] p-3 text-white transition-all active:scale-95"
            type="button"
            @click="handleCopy"
          >
            <span
              class="relative h-3 w-3 flex"
            >
              <span
                class="absolute h-full w-full inline-flex animate-ping rounded-full bg-[#CC171D] opacity-75"
              />

              <span
                class="relative h-3 w-3 inline-flex rounded-full bg-[#CC171D]"
              />
            </span>
            {{ contactEmailUrl }}
          </button>
        </div>
      </div>

      <!-- Github活动图 -->

      <!-- github-readme-stats -->
      <div
        class="col-span-1 row-span-2 max-sm:col-span-3"
      >
        <img
          src="https://github-readme-stats.vercel.app/api?username=weiShaoY&theme=chartreuse-dark&show_icons=true&hide_border=true&count_private=true&locale=cn&bg_color=0E0E10&line_height=36&title_color=BFFFBF"
          alt=""
          class="h-full w-full"
        >
      </div>

      <div
        class="col-span-1 row-span-2 max-sm:col-span-3"
      >
        <img
          src="https://github-readme-stats.vercel.app/api/top-langs/?username=weiShaoY&theme=chartreuse-dark&hide_border=true&include_all_commits=true&count_private=truechart&locale=cn&bg_color=0E0E10&layout=compact&title_color=BFFFBF"
          alt=""
          class="h-60 w-full"
        >
      </div>

      <div
        class="col-span-1 row-span-2 max-sm:col-span-3"
      >
        <img
          src="https://github-profile-summary-cards.vercel.app/api/cards/productive-time?username=weiShaoY&theme=merko"
          alt=""
          class="h-60 w-full"
        >

        <!-- <img
          src="https://github-readme-activity-graph.vercel.app/graph?username=weiShaoY&theme=merko&hide_border=true&radius=8&bg_color=0E0E10&line=00ff00&point=ffffff&custom_title=Github%20%E8%B4%A1%E7%8C%AE%E5%9B%BE"
          alt=""
          class="h-[212px] w-full"
        > -->

        <!-- <img
          src="https://pixel-profile.vercel.app/api/github-stats?username=weiShaoY&theme=crt&pixelate_avatar=false"
          alt=""
          class="h-[212px] w-full"
        > -->
      </div>

    </div>

  </section>
</template>

// src/pages/home/about/components/info/index.tsx
import { useState } from "react";

import Earth from "@/canvas/earth";

import Button from "./button";

import copyImg from "./images/copy.svg";
import gridImage3 from "./images/grid3.png";
import gridImage4 from "./images/grid4.png";
import tickImg from "./images/tick.svg";

import Tech from "@/canvas/tech";

const About = () => {
	const [hasCopied, setHasCopied] = useState(false);

	const handleCopy = () => {
		navigator.clipboard.writeText(" adrian@jsmastery.pro");
		setHasCopied(true);

		setTimeout(() => {
			setHasCopied(false);
		}, 2000);
	};

	return (
		<section className="sm:px-10 px-5 my-20 " id="info">
			<div className="grid xl:grid-cols-3 xl:grid-rows-6 md:grid-cols-2 grid-cols-1 gap-5 h-full">
				<div className="xl:col-span-2 xl:row-span-3">
					<div className="w-full h-full border border-[#1c1c21] bg-[#0E0E10] rounded-lg sm:p-7 p-4 flex flex-col gap-5">
						<div className="w-full sm:h-[266px] h-fit cursor-pointer">
							<Tech />
						</div>
						<div>
							<p className="text-xl font-semibold mb-2 text-white">技术栈</p>
							<p className="text-[#afb0b6] text-base">
								我擅长各种语言、框架和工具，它们让我能够构建强大且可扩展的应用程序
							</p>
						</div>
					</div>
				</div>

				<div className="col-span-1 xl:row-span-4">
					<div className="w-full h-full border border-[#1c1c21] bg-[#0E0E10] rounded-lg sm:p-7 p-4 flex flex-col gap-5">
						<div className="rounded-3xl w-full  sm:h-[326px] h-fit  flex justify-center items-center">
							<Earth height={326} />
						</div>
						<div>
							<p className="text-xl font-semibold mb-2 text-white">
								我对时区、通讯和位置非常灵活
							</p>
							<p className="text-[#afb0b6] text-base">
								我居住在湖南长沙，愿意进行远程工作。
							</p>
							<Button name="联系我" isBeam containerClass="w-full mt-10" />
						</div>
					</div>
				</div>

				<div className="xl:col-span-2 xl:row-span-3">
					<div className="w-full h-full border border-[#1c1c21] bg-[#0E0E10] rounded-lg sm:p-7 p-4 flex flex-col gap-5">
						<img
							src={gridImage3}
							alt="grid-3"
							className="w-full sm:h-[266px] h-fit object-contain"
						/>

						<div>
							<p className="text-xl font-semibold mb-2 text-white">
								我对编码的热情
							</p>
							<p className="text-[#afb0b6] text-base">
								我喜欢通过代码解决问题和构建事物。编程不仅仅是我的职业，更是我的激情所在。我喜欢探索新技术并提高自己的技能。
							</p>
						</div>
					</div>
				</div>

				<div className="xl:col-span-1 xl:row-span-2">
					<div className="w-full h-full border border-[#1c1c21] bg-[#0E0E10] rounded-lg sm:p-7 p-4 flex flex-col gap-5">
						<img
							src={gridImage4}
							alt="grid-4"
							className="w-full md:h-[126px] sm:h-[276px] h-fit object-cover sm:object-top"
						/>

						<div className="space-y-2">
							<p className="text-[#afb0b6] text-base  text-center">联系我</p>
							<div
								className="cursor-pointer flex justify-center items-center gap-2 h-10"
								onClick={handleCopy}
							>
								<img
									src={hasCopied ? tickImg : copyImg}
									alt="copy"
									className="h-8 w-8"
								/>
								<p className="lg:text-2xl md:text-xl  font-medium bg-gradient-to-r from-[#BEC1CF] from-60% via-[#D5D8EA] via-60% to-[#D5D8EA] to-100% bg-clip-text  text-white">
									1604705673@qq.com
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
};

export default About;
